export const topicPatterns = {
    symptoms: [
        "fever", "cough", "headache", "chills", "fatigue", "sore throat", "muscle pain", 
    "nausea", "vomiting", "diarrhea", "abdominal pain", "chest pain", "shortness of breath", 
    "dizziness", "lightheadedness", "loss of appetite", "weight loss", "weight gain", 
    "swelling", "rash", "itching", "hives", "blurred vision", "double vision", 
    "sensitivity to light", "ringing in ears", "hearing loss", "ear pain", "runny nose", 
    "nasal congestion", "sneezing", "dry mouth", "sore gums", "toothache", "jaw pain", 
    "difficulty swallowing", "heartburn", "indigestion", "bloating", "constipation", 
    "blood in stool", "mucus in stool", "urinary urgency", "urinary frequency", "persistent cough with blood",
    "painful urination", "blood in urine", "pelvic pain", "lower back pain", "joint pain", 
    "joint stiffness", "severe headache", "vision changes", "dehydration", "muscle weakness", "tingling", "numbness", "tremors", 
    "seizures", "fainting", "memory loss", "confusion", "anxiety", "depression", 
    "irritability", "insomnia", "loss of weight", "night sweats", "hot flashes", "excessive thirst", 
    "frequent urination", "dry skin", "hair loss", "bruising", "bleeding gums", 
    "sudden vision loss", "neck pain", "shoulder pain", "upper back pain", 
    "hip pain", "knee pain", "ankle pain", "foot pain", "weakness in arms", 
    "weakness in legs", "cramping", "spasms", "loss of balance", "difficulty walking", 
    "difficulty breathing", "wheezing", "coughing up blood", "hoarseness", 
    "chronic fatigue", "increased sweating", "excessive yawning", "pale skin", 
    "jaundice", "hemoptysis", "blue lips", "cyanosis", "shakiness", "twitching", "cold hands", 
    "cold feet", "sensitivity to cold", "sensitivity to heat", "chest tightness", 
    "palpitations", "irregular heartbeat", "slow heartbeat", "rapid heartbeat", 
    "high blood pressure", "low blood pressure", "light sensitivity", "eye pain", 
    "bloodshot eyes", "dry eyes", "watery eyes", "swollen eyes", "bulging eyes", 
    "discharge from eyes", "eye floaters", "flashing lights", "loss of vision in one eye", 
    "yellowing of eyes", "difficulty concentrating", "mood swings", "uncontrolled crying", 
    "irritated skin", "peeling skin", "scaly patches", "hair thinning", "split nails", 
    "brittle nails", "chapped lips", "cracked lips", "ulcers", "swollen lymph nodes", 
    "lumps", "skin sores", "burning sensation", "frequent infections", "slow healing", 
    "excessive hair growth", "absent periods", "heavy periods", "painful periods", 
    "vaginal discharge", "vaginal itching", "breast tenderness", "breast lumps", 
    "nipple discharge", "difficulty urinating", "nocturia", "involuntary urination", 
    "pain during intercourse", "decreased libido", "erectile dysfunction", 
    "premature ejaculation", "painful ejaculation", "testicular pain", 
    "enlarged prostate", "enlarged testicles", "shrunken testicles", "foot swelling", 
    "hand swelling", "face swelling", "lips swelling", "tongue swelling", 
    "swollen joints", "unexplained weight change", "hair texture changes", 
    "nail texture changes", "frequent nosebleeds", "persistent cough", 
    "frequent headaches", "excessive daytime sleepiness", "snoring", 
    "unusual sleep patterns", "loss of consciousness", "difficulty seeing at night", 
    "halos around lights", "pulsating headache", "frequent yawning", "weak pulse", 
    "increased heart rate", "swollen ankles", "pain in toes", "discoloration of fingers", 
    "red skin", "puffy eyelids", "drooping eyelid", "involuntary eye movements", 
    "difficulty with fine motor skills", "generalized weakness", "chronic pain", 
    "sharp pain", "burning pain", "tingling in extremities", "difficulty bending joints", 
    "stiff neck", "stiff back", "difficulty climbing stairs", "pain when sitting", 
    "pain when standing", "unable to turn head", "inability to lift arms", 
    "difficulty raising hand", "dry scalp", "flaky scalp", "brittle hair", 
    "excessive sweating at night", "constant cold feeling", "frequent chills", 
    "muscle cramps at night", "pain in fingers", "pain in wrist", "pain in elbow", 
    "pain in shoulder", "pain in hip", "pain in thighs", "restlessness", 
    "inability to focus", "feeling faint", "feeling weak", "feeling hot", 
    "feeling cold", "constant hunger", "constant thirst", "loss of taste", 
    "loss of smell", "sensitive to odors", "difficulty hearing", "ringing in the ears", 
    "sensitivity to sounds", "difficulty forming sentences", "slurred speech", 
    "hoarse voice", "loss of voice", "cracked skin", "sores in mouth", 
    "painful sores", "blisters", "blood in mouth", "gum pain", "swollen gums", 
    "frequent mouth ulcers", "taste of blood", "bad breath", "sensitive teeth", 
    "grinding teeth", "clenching jaw", "dry throat", "tickling in throat", 
    "hoarse throat", "pain in throat", "choking sensation", "tight throat", 
    "excessive belching", "heart palpitations", "feeling of fullness", 
    "difficulty digesting", "constipation", "diarrhea", "frequent urination", 
    "cloudy urine", "foul-smelling urine", "burning sensation during urination", 
    "blood in urine", "pain in lower abdomen", "pelvic pressure", 
    "feeling of incomplete emptying", "nighttime urination", "frequent urinary tract infections", 
    "loss of bladder control", "excessive sweating", "sensitivity to sweat", 
    "muscle twitching", "muscle soreness", "aching muscles", "pain in groin", 
    "difficulty moving limbs", "involuntary movements", "abnormal sensations", 
    "difficulty breathing", "shallow breathing", "increased heart rate", 
    "decreased heart rate", "racing heart", "fluttering heart", "pain with deep breathing", 
    "shortness of breath while lying down", "chronic wheezing", "sleep disturbances", 
    "unrefreshing sleep", "frequent yawning", "night terrors", "chronic fatigue syndrome", 
    "sweaty palms", "sweaty feet", "unexplained bruising", "persistent itchiness", 
    "hair breakage", "dry eyes", "sensitive eyes", "night blindness", "muscle rigidity", 
    "muscle twitching", "clumsiness", "difficulties with balance", "persistent bad taste", 
    "metallic taste", "persistent sore throat", "dysphagia", "esophageal pain", 
    "chronic sinus congestion", "persistent runny nose", "nasal discharge", 
    "chronic cough", "excessive drooling", "painful swallowing", "persistent nausea", 
    "frequent vomiting", "early satiety", "persistent abdominal bloating", 
    "painful abdominal cramping", "chronic pelvic pain", "persistent joint stiffness", 
    "painful menstrual cramps", "irregular menstrual cycles", "pain during menstruation", 
    "painful urination", "increased urination frequency", "painful ejaculation", 
    "painful intercourse", "pain in testicles", "testicular swelling", "abnormal semen color", 
    "changes in libido", "unexplained abdominal weight gain", "muscle tension", 
    "frequent yawning", "difficulty staying awake", "discomfort while sitting", 
    "discomfort while standing", "persistent vertigo", "lightheadedness", 
    "chronic light sensitivity", "sudden mood changes", "impaired coordination", 
    "difficulty with fine motor tasks", "difficulty with large motor tasks", 
    "excessive sleepiness during day", "excessive daytime sleepiness", "excessive nighttime urination",
     "abnormal heart rhythms", "apnea", "arthralgia", "asthenia", "belching", 
     "bradycardia", "breathlessness", "cachexia", "chest discomfort", "chronic dry cough", 
     "chronic hoarseness", "chronic pruritus", "confusion", "coryza", "coughing up mucus", 
     "delirium", "depersonalization", "dermatitis", "difficulty breathing deeply", 
     "difficulty moving", "dyspepsia", "ear fullness", "ear ringing", "easy bruising", 
     "elevated blood pressure", "epistaxis", "excessive drooling", "excessive hunger", 
     "excessive sweating during the day", "eye discomfort", "eye irritation", "feeling disoriented", 
     "feeling jittery", "feeling out of breath", "feeling shaky", "fever blisters", "focal seizures", 
     "frequent nosebleeds", "frequent vomiting of blood", "gastrointestinal bleeding", "giddiness", 
     "gum swelling", "hallucinations", "heart murmur", "increased appetite", "increased sensitivity to touch", 
     "jitteriness", "localized pain", "muscle fatigue", "muscle spasms", "nasal itching", 
     "nausea after eating", "persistent abdominal pain", "persistent dizziness", "persistent sweating", 
     "pressure in the chest", "prickling sensation", "prolonged bleeding", "pyrexia", "sensitivity to light", 
     "sensitivity to noise", "sensitive to touch", "skin discoloration", "skin inflammation", 
     "sudden confusion", "tenderness in abdomen", "tenderness in joints", "trembling", 
     "unexplained fatigue", "unexplained weight loss", "visual disturbances", "vomiting blood", 
     "weak grip strength", "weight changes", "yellowing of skin", "yawning excessively", 
     "abdominal tenderness", "chronic hiccups", "cognitive impairment", "dry cough at night", 
     "facial flushing", "gastric reflux", "giddiness", "irregular menstrual bleeding", 
     "metallic breath", "nighttime leg cramps", "persistent burning sensation", "persistent thirst", 
     "phlegm production", "swollen abdominal area", "swollen joints in fingers", "thick mucus production", 
     "trouble speaking clearly", "unexplained bruising", "vertiginous sensations", "wheezing when lying down", 
     "yellowish discoloration of skin", "abnormal urine color", "cognitive disorientation", 
     "decreased appetite", "difficulty lifting objects", "difficulty with memory", "difficulty with reasoning",
     "abdominal distention", "allergic reaction", "altered mental status", "bloody discharge", 
     "bone pain", "bloating sensation", "bradykinesia", "coughing up phlegm", "cyanotic skin", 
     "delayed wound healing", "discolored urine", "dull pain", "earache", "excessive thirst at night", 
     "feeling of heaviness", "fibromyalgia", "frequent sneezing", "frostbite", "gastric pain", 
     "hallucinations", "hemorrhoids", "hyperpigmentation", "increased thirst", "involuntary muscle movements", 
     "irregular periods", "lip swelling", "loss of muscle mass", "metabolic syndrome", "nail discoloration", 
     "persistent itching", "pustules", "redness around the eyes", "restless legs", "sensitive to pressure", 
     "slurred speech", "stiffness in muscles", "swollen abdomen", "sweating excessively", "throat tightness", 
     "tinnitus", "unexplained fainting", "unusual smells", "vision disturbances", "vivid dreams", 
     "wheezing during physical exertion", "yellowish discharge", "zinc deficiency",
     "feeling of tightness in chest", "dry cough", "pain when breathing", 
     "burning sensation in chest", "persistent cough", "constant throat clearing", 
     "dull ache", "chronic sore throat", "frequent belching", "unexplained bruises",
     "painful joints", "unusual muscle weakness", "muscle wasting", "muscle tension", 
     "painful urination", "difficulty swallowing liquids", "painful swallowing solids",
     "bleeding from the gums", "pain when eating", "abdominal cramping", "chronic nausea",
     "persistent vomiting", "pain behind the eyes", "feeling of pressure in the head",
     "unexplained headaches", "sharp chest pain", "pain in the ribs", "constant need to urinate",
     "painful menstrual cycles", "difficulty getting to sleep", "difficulty staying asleep",
     "waking up with headaches", "pain in the neck", "pain in the jaw", "pain in the face",
     "sensitivity to changes in weather", "discomfort after eating", "difficulty breathing deeply",
     "pain in the lower back", "pain in the upper back", "pain in the pelvis", "cramps in legs",
     "frequent leg pain", "pain in the arms", "pain in the wrists", "pain in the hands",
     "sensation of something stuck in throat", "difficulty moving the eyes", "sensitivity to temperature changes",
     "unexplained skin changes", "discoloration of the skin", "swollen abdomen", "pain in the hips",
     "chronic sinus pain", "dysphagia", "hoarseness of voice", "chronic mucus production",
     "painful bowel movements", "difficulty urinating", "pain when passing stool", 
     "pain in the groin", "tender skin", "coldness in extremities", "painful fingertips",
     "painful heels", "pain in the arches of the feet", "sensitivity to touch", "pain when moving",
     "recurrent fevers", "shivering", "dull back pain", "pain during sexual activity", 
     "frequent urination at night", "disturbed sleep patterns", "constant yawning",
     "muscle cramps during sleep", "pain with swallowing", "hoarseness in voice", 
     "feeling of fullness in the ears", "pain in the forehead", "pain in the nose",
     "pain in the sinuses", "ear discomfort", "frequent nosebleeds", "sensitivity to light",
     "pain in the rib cage", "pain in the groin area", "muscle soreness", "chronic fatigue",
     "difficulty breathing through the nose", "excessive thirst at night", "frequent hiccups",
     "swelling in legs", "swelling in arms", "pain in joints after exercise", 
     "pain in the lower limbs", "persistent cough with mucus", "persistent itchiness in the throat",
     "pain while sitting", "pain while standing", "difficulty breathing while lying down",
     "discomfort in the stomach", "feeling of heaviness in the chest", "pain in the upper abdomen",
     "sensitivity to touch in skin", "numbness in limbs", "muscle weakness in legs",
     "involuntary muscle movements", "itchy scalp", "pain in the joints of the fingers", 
     "pain in the joints of the toes", "pain in the knuckles", "feeling of heaviness in limbs",
     "pain in the pelvic region", "pain when bending", "feeling of tension in muscles",     "inspiratory stridor", "expiratory stridor", "positional stridor",
     "suprasternal retractions", "subcostal retractions", "intercostal retractions",
     "nasal flaring", "paradoxical breathing", "accessory muscle use",
     "tracheal tugging", "stertor", "bronchial breathing sounds",
     "decreased breath sounds", "prolonged expiratory phase", "forced expiration",
     "barrel chest appearance", "pursed lip breathing", "orthopneic positioning",
     "tripod positioning", "laryngeal spasm", "vocal cord dysfunction",
     
     
     "irregular breathing pattern", "cluster breathing", "ataxic breathing",
     "biot breathing", "cheyne-stokes breathing", "kussmaul breathing",
     "apneustic breathing", "sighing respiration", "shallow rapid breathing",
     "thoracoabdominal asynchrony", "periodic breathing", "respiratory alternans",
     "forced inspiratory breathing", "gasping respirations", "agonal breathing",
     "respiratory muscle fatigue", "diaphragmatic breathing difficulty",
     "paradoxical abdominal movement", "tachypnea at rest", "bradypnea",
     
     
     "paroxysmal cough", "brassy cough", "seal bark cough",
     "morning productive cough", "evening dry cough", "positional cough",
     "exercise-induced cough", "post-viral cough", "stress-induced cough",
     "metallic cough", "bifid cough", "spasmodic cough",
     "nocturnal cough paroxysms", "cough syncope", "cough with speaking",
     "cough with laughing", "cough with eating", "cough with drinking",
     "throat-clearing cough", "chronic refractory cough",
     
     
     "rusty sputum", "pink frothy sputum", "green streaked sputum",
     "blood-tinged sputum", "thick yellow sputum", "foamy sputum",
     "mucoid sputum", "purulent sputum", "blood-streaked sputum",
     "coffee-ground sputum", "foul-smelling sputum", "morning sputum production",
     "difficulty expectorating", "sticky sputum", "clear frothy sputum",
     "tenacious sputum", "copious sputum", "scanty sputum",
     "white pearl sputum", "black-colored sputum",
     
     
     "burning in chest wall", "chest wall tenderness", "pleuritic chest pain",
     "substernal chest pressure", "chest tightness with exercise",
     "costal margin tenderness", "chest wall numbness", "radiating chest discomfort",
     "burning sensation in airways", "chest wall hypersensitivity",
     "inspiratory chest pain", "expiratory chest pain", "positional chest pain",
     "chest wall muscle spasms", "rib cage tenderness", "sternal pressure",
     "precordial catch", "chest wall burning", "thoracic spine pain",
     "costume jewelry allergy on chest",
     
     
     "exercise-induced bronchospasm", "post-exercise wheeze",
     "activity-related breathlessness", "exertional dyspnea",
     "reduced exercise tolerance", "breathing difficulty climbing stairs",
     "breathlessness with daily activities", "post-activity cough",
     "exercise-induced chest pain", "activity-induced wheeze",
     "breathlessness on minimal exertion", "exercise-induced stridor",
     "post-exercise throat tightness", "activity-related chest tightness",
     "exercise-induced respiratory fatigue", "breathlessness when bending",
     "respiratory limitation to exercise", "post-exercise respiratory distress",
     "activity-induced respiratory symptoms", "exercise-induced hypoxemia",
     
     
     "nocturnal dyspnea", "sleep-onset breathlessness",
     "positional nocturnal cough", "sleep-related wheezing",
     "nocturnal chest tightness", "sleep-onset cough",
     "morning chest congestion", "nocturnal respiratory distress",
     "sleep-related stridor", "positional sleep breathlessness",
     "nocturnal respiratory anxiety", "sleep-related chest pain",
     "morning respiratory fatigue", "nocturnal air hunger",
     "sleep-position breathing difficulty", "nocturnal breath sounds",
     "sleep-related respiratory events", "morning breathing difficulty",
     "nocturnal respiratory symptoms", "sleep-related breathing changes",
     
     
     "cold air sensitivity", "humidity-induced symptoms",
     "weather-change respiratory symptoms", "altitude-related breathlessness",
     "air pollution sensitivity", "temperature-change breathing difficulty",
     "seasonal respiratory symptoms", "indoor air quality reactions",
     "chemical sensitivity breathing", "environmental trigger response",
     "allergic respiratory reaction", "irritant-induced symptoms",
     "occupational breathing problems", "workplace respiratory symptoms",
     "exposure-related breathing changes", "environmental asthma symptoms",
     "trigger-induced respiratory events", "situational breathing difficulties",
     "context-specific respiratory symptoms", "exposure-related breathing problems",
     
     
     "voice changes with breathing", "respiratory vocal fatigue",
     "breathing-related voice changes", "upper airway irritation",
     "laryngeal breathing symptoms", "throat-breathing coordination issues",
     "vocal cord breathing problems", "upper airway breathing noise",
     "breathing-related voice strain", "respiratory voice changes",
     "upper airway breathing difficulty", "laryngeal breathing dysfunction",
     "voice-breath coordination problems", "breathing pattern voice changes",
     "upper respiratory vocal symptoms", "breathing-related voice problems",
     "respiratory-vocal coordination issues", "upper airway breathing symptoms",
     "voice-breath pattern changes", "respiratory vocal dysfunction",
     
     
     "air hunger", "inability to take deep breath", "chest wall movement asymmetry",
     "respiratory muscle weakness", "breathing pattern disorder",
     "respiratory awareness", "breathing coordination difficulty",
     "respiratory effort sensation", "breathing pattern anxiety",
     "respiratory muscle tension", "breathing rhythm disruption",
     "respiratory feedback sensation", "breathing pattern changes",
     "respiratory consciousness", "breathing difficulty patterns",
     "respiratory cycle changes", "breathing mechanics problems",
     "respiratory timing issues", "breathing synchrony problems",
     "respiratory control difficulties", "food regurgitation when lying down", "burning after spicy foods",
    "difficulty swallowing pills", "pain when swallowing cold drinks",
    "pain when swallowing hot drinks", "sensation of food stuck in upper chest",
    "bitter taste in morning", "burning in throat after eating",
    "difficulty swallowing saliva", "gagging when brushing teeth",
    "globus sensation after meals", "pain behind breastbone when eating",
    "regurgitation of undigested food", "sour taste after lying down",
    "upper abdominal burning at night", "burning in throat while sleeping",
    "chest pain after large meals", "difficulty swallowing dry foods",
    "early satiety with liquids", "feeling of tightness after eating",
    "food getting stuck momentarily", "heartburn during exercise",
    "hiccups after carbonated drinks", "hoarseness after eating",
    "increased salivation after meals", "painful swallowing on right side",
    "painful swallowing on left side", "regurgitation during exercise",
    "retrosternal burning at night", "sour taste with empty stomach",
    "upper abdominal fullness", "burning in upper abdomen",
    "chest pressure after eating", "difficulty initiating swallow",
    "early morning nausea", "feeling of lump during swallowing",
    "food sticking at same spot", "heartburn when bending over",
    "hiccups with hot drinks", "increased belching after dairy",
    "painful swallowing with bread", "regurgitation of bitter fluid",
    "retrosternal discomfort", "sour taste in throat",
    "upper abdominal distention", "waterbrash symptoms",
    "chest burning while lying flat", "difficulty swallowing liquids first",
    "esophageal food impaction", "feeling of obstruction in throat",
    "food sticking temporarily", "heartburn with caffeine",
    "hiccups with cold foods", "indigestion after fatty foods",
    "pain on swallowing at night", "regurgitation of acid taste",
    "retrosternal pain", "stabbing chest pain after eating",
    "upper abdominal gurgling", "wet burps after meals",

    
    "alternating loose firm stools", "bowel urgency after eating",
    "cramping before bowel movement", "diarrhea with fasting",
    "excessive flatulence at night", "floating stools in morning",
    "incomplete evacuation feeling", "left lower quadrant pain",
    "mucus coating on stools", "pain relieved by defecation",
    "right lower quadrant pain", "small frequent bowel movements",
    "stool color variations", "sudden bowel urgency",
    "tenesmus after meals", "alternating constipation diarrhea",
    "bowel movement difficulties", "cramping during bowel movement",
    "diarrhea with stress", "fecal incontinence when passing gas",
    "foamy stools", "intestinal rumbling sounds",
    "left-sided abdominal pain", "narrow pencil-like stools",
    "painful bowel movements", "ribbon-like stools",
    "soft mushy stools", "stool consistency changes",
    "sudden urge to defecate", "visible food in stool",
    "anal itching after bowel movement", "bowel pattern changes",
    "cramping lower abdomen", "diarrhea with exercise",
    "fatty looking stools", "frequent incomplete stools",
    "irregular bowel habits", "liquid stool after solid",
    "nocturnal bowel movements", "painful gas passing",
    "rectal pain with sitting", "solid stool after liquid",
    "stool odor changes", "straining with bowel movements",
    "undigested food in stool", "anal pain during defecation",
    "bowel sounds after eating", "constipation alternating with normal",
    "diarrhea with certain foods", "feeling of incomplete passing",
    "frequent unsuccessful urge", "large volume stools",
    "loose stools in morning", "oily droplets in toilet",
    "pellet-like stools", "rectal pressure sensation",
    "spontaneous bowel movements", "stool urgency after eating",
    "straining to pass gas", "visible mucus in stool",

    
    "band-like abdominal pain", "colicky central pain",
    "cramping around navel", "diffuse abdominal discomfort",
    "epigastric pain after eating", "flank pain on movement",
    "generalized abdominal tenderness", "hunger pain relief with food",
    "intermittent sharp pain", "knife-like pain in abdomen",
    "left upper quadrant pain", "migrating abdominal pain",
    "pain worse with movement", "periumbilical pain",
    "right upper quadrant pain", "burning abdominal pain",
    "constant dull ache", "cramping before meals",
    "early morning abdominal pain", "exercise-induced abdominal pain",
    "food-related abdominal pain", "gnawing epigastric pain",
    "hunger-like pain", "intense colicky pain",
    "left lower abdominal pain", "middle abdominal pain",
    "night time abdominal pain", "pain relieved by eating",
    "postprandial abdominal pain", "right-sided abdominal pain",
    "burning in lower abdomen", "constant upper abdominal pain",
    "cramping mid-abdomen", "eating-induced pain",
    "fasting abdominal pain", "gradual onset pain",
    "hunger pains at night", "intermittent abdominal pain",
    "left-sided belly pain", "morning abdominal discomfort",
    "non-radiating pain", "pain worse after eating",
    "pressure-like abdominal pain", "right lower abdominal pain",
    "boring abdominal pain", "chronic intermittent pain",
    "cramping pelvic area", "episodic abdominal pain",
    "fixed abdominal pain", "gripping abdominal pain",
    "hyperactive bowel sounds", "intense epigastric pain",
    "localized abdominal pain", "morning hunger pain",
    "pain during exercise", "pain with deep breath",
    "radiating abdominal pain", "right upper belly pain",
    "sharp shooting pain", "stabbing abdominal pain",

    
    "acidic taste after meals", "belching with bitter taste",
    "burning during digestion", "delayed gastric emptying symptoms",
    "early fullness with meals", "feeling of indigestion",
    "garlic taste in mouth", "heavy feeling after eating",
    "immediate postprandial fullness", "loss of appetite midday",
    "metallic taste while eating", "nausea after dairy",
    "painful digestion", "quick satiety",
    "reduced meal tolerance", "acid reflux when exercising",
    "bloating after small meals", "burning upper stomach",
    "difficulty digesting fats", "early satiety with solids",
    "feeling of slow digestion", "gastric burning sensation",
    "hunger despite eating", "increased appetite at night",
    "loss of taste for meat", "morning appetite loss",
    "nausea between meals", "pain during digestion",
    "queasy feeling after eating", "regurgitation while eating",
    "appetite changes cyclically", "bloating immediately after eating",
    "burning with empty stomach", "digestion noise",
    "easy satiety", "feeling overly full",
    "gastric pain after eating", "hunger pain at night",
    "increased thirst after eating", "loss of taste for sweets",
    "motion sickness after eating", "nausea during meals",
    "painful stomach growling", "queasy stomach morning",
    "salt cravings after eating", "appetite loss with smells",
    "bloating with liquids", "burning without eating",
    "distention after meals", "eating aversion",
    "food aversion development", "gastric upset with oils",
    "hunger despite fullness", "increased burping with meals",
    "loss of taste sensation", "nausea anticipating food",
    "overwhelming fullness", "post-meal drowsiness",
    "rapid fullness", "sweet cravings after eating",

    
    "abdominal muscle spasms", "audible stomach sounds",
    "borborygmi after eating", "constant stomach awareness",
    "difficulty lying on side", "early morning stomach pain",
    "feeling of bubbles in stomach", "gurgling when hungry",
    "hiatal hernia symptoms", "increased flatulence with dairy",
    "left side lying discomfort", "morning stomach upset",
    "nausea on empty stomach", "pain worse lying down",
    "right side lying pain", "abdominal wall pain",
    "back pain with bloating", "burning in stomach at night",
    "distention with gas", "eating position discomfort",
    "feeling of movement in stomach", "growling stomach when full",
    "hiccups with bloating", "intestinal hypersensitivity",
    "liver area discomfort", "motion sickness prone",
    "nausea with position change", "pelvic floor pressure",
    "rumbling empty stomach", "abdominal wall tenderness",
    "belching with stomach pain", "burning under ribs",
    "diurnal symptom variation", "epigastric pulsation",
    "food sitting in stomach", "gurgles with movement",
    "high-pitched bowel sounds", "left upper belly tension",
    "lower abdominal weakness", "nausea after antibiotics",
    "nocturnal digestive pain", "periodic abdominal spasms",
    "right upper belly soreness", "ambulatory abdominal pain",
    "bilious taste morning", "cold sensation in stomach",
    "dry heaving morning", "epigastric flutter",
    "forcing food down", "gurgling under ribs",
    "hollow sensation stomach", "left-sided fullness",
    "mid-abdominal pressure", "nausea during exercise",
    "noisy stomach digestion", "persistent dry heaves",
    "right-sided fullness", "upper GI awareness",     "racing heart during rest", "skipped beats while lying down", 
    "fluttering sensation after meals", "heart pounding in throat",
    "irregular heartbeat at night", "sensation of heart stopping",
    "sudden heart rate changes", "heart racing after minor activity",
    "palpitations during deep breathing", "heart flutter when bending",
    "bouncing heart sensation", "rapid heartbeat when standing",
    "heart pounding in ears", "missed beats during exercise",
    "heart flutter with anxiety", "racing heart after caffeine",
    "pounding heart in morning", "irregular rhythm when tired",
    "heart racing while sitting", "fluttering after alcohol",
    "sensation of extra heartbeats", "heart pounding when lying left",
    "rapid pulse after eating", "heart racing in pregnancy",
    "skipped beats with stress", "palpitations after heavy meal",
    "heart flutter during fever", "racing heart before periods",
    "irregular beats when relaxing", "heart pounding in heat",
    "palpitations during fasting", "heart racing with dehydration",
    "flutter sensation at rest", "pounding after cold drinks",
    "rapid heart during meditation", "skipped beats before sleep",
    "heart racing with medication", "irregular rhythm after exercise",
    "palpitations with hot flashes", "heart pounding in cold",
    "flutter during public speaking", "racing heart with low blood sugar",
    "skipped beats with coughing", "pounding heart when startled",
    "heart flutter with indigestion", "racing pulse when dehydrated",
    "irregular beats during illness", "heart pounding after nightmare",
    "palpitations with deep breath", "flutter during hot weather",
    "racing heart with vertigo", "skipped beats during fever",
    "heart pounding with anxiety", "irregular rhythm when hungry",
    "palpitations while speaking", "heart flutter during period",
    "racing pulse with emotions", "skipped beats with fatigue",
    "heart pounding after bending", "flutter with empty stomach",
    "rapid beats during rest", "irregular rhythm after meals",
    "palpitations in pregnancy", "heart flutter with stress",
    "racing pulse during illness", "skipped beats with alcohol",
    "heart pounding in silence", "flutter during exercise",
    "rapid beats with fever", "irregular rhythm when excited",
    "palpitations after surgery", "heart flutter when tired",
    "racing pulse with anemia", "skipped beats during stress",
    "heart pounding with fever", "flutter during menopause",
    "rapid beats with anxiety", "irregular rhythm when hot",
    "palpitations while lying", "heart flutter after eating",
    "racing pulse with thyroid", "skipped beats during illness",
    "heart pounding with stress", "flutter during pregnancy",
    "rapid beats with pain", "irregular rhythm when cold",
    "palpitations at night", "heart flutter with medication",
    "racing pulse with infection", "skipped beats during exercise",
    "heart pounding with fatigue", "flutter during anxiety",
    "rapid beats with emotion", "irregular rhythm when tired",
    "palpitations when walking", "heart flutter after caffeine",
    "racing pulse with medication", "skipped beats during rest",
    "heart pounding with illness", "flutter during illness",
    "rapid beats with stress", "irregular rhythm when anxious",
    "palpitations with pain", "heart flutter after alcohol",
    "racing pulse with pregnancy", "skipped beats during sleep",
    "heart pounding with anemia", "flutter during exercise",

    
    "sharp chest pain left side", "dull ache under breastbone",
    "burning chest pain with breathing", "pressure pain in center chest",
    "stabbing pain near heart", "crushing chest sensation",
    "chest tightness with exercise", "radiating pain to left arm",
    "pinching pain in chest", "squeezing chest sensation",
    "chest pain with deep breath", "throbbing chest discomfort",
    "pressure behind breastbone", "chest pain with movement",
    "burning sensation in chest", "sharp pain with coughing",
    "dull chest pain at rest", "chest pressure when lying",
    "stabbing pain with breathing", "radiating pain to jaw",
    "chest tightness at night", "crushing pain with exertion",
    "pinching sensation left chest", "squeezing pain at rest",
    "chest pain after eating", "throbbing left chest pain",
    "pressure pain with stress", "chest pain in morning",
    "burning pain after meals", "sharp pain when bending",
    "dull ache with exercise", "chest pressure with anxiety",
    "stabbing pain at night", "radiating pain to back",
    "chest tightness with stress", "crushing pain at rest",
    "pinching pain right chest", "squeezing sensation with activity",
    "chest pain with anxiety", "throbbing pain at night",
    "pressure with deep breath", "chest pain after exercise",
    "burning sensation at rest", "sharp pain with stress",
    "dull pain with movement", "chest pressure during sleep",
    "stabbing pain after meals", "radiating pain to shoulder",
    "chest tightness in morning", "crushing sensation with breathing",
    "pinching pain during rest", "squeezing pain with stress",
    "chest pain while sleeping", "throbbing sensation with exercise",
    "pressure pain at night", "chest pain with heat",
    "burning pain with activity", "sharp pain during rest",
    "dull ache after eating", "chest pressure with movement",
    "stabbing pain with stress", "radiating pain to neck",
    "chest tightness after meals", "crushing pain with movement",
    "pinching sensation with breath", "squeezing chest at night",
    "chest pain with cold", "throbbing pain with activity",
    "pressure with movement", "chest pain during stress",
    "burning sensation after exercise", "sharp pain at night",
    "dull pain during rest", "chest pressure after eating",
    "stabbing sensation with activity", "radiating pain to arm",
    "chest tightness with breathing", "crushing sensation at rest",
    "pinching pain with stress", "squeezing pain during exercise",
    "chest pain with breathing", "throbbing sensation at rest",
    "pressure after exercise", "chest pain with activity",
    "burning pain at night", "sharp pain with activity",
    "dull ache during stress", "chest pressure with breathing",
    "stabbing pain during rest", "radiating pain to chest",
    "chest tightness during exercise", "crushing pain with stress",
    "pinching sensation at night", "squeezing sensation at rest",
    "chest pain with stress", "throbbing pain with breathing",
    "pressure with activity", "chest pain with breathing",
    "burning sensation with stress", "sharp pain after exercise",
    "dull pain at night", "chest pressure during activity",
    "stabbing sensation with breathing", "radiating pain with stress",
    "chest tightness at rest", "crushing sensation with activity",
    "pinching pain with breathing", "squeezing pain with movement",
    "chest pain during activity", "throbbing sensation with stress",
    "pressure at rest", "chest pain with movement",
    "burning pain with breathing", "sharp sensation at rest",
    "dull ache with stress", "chest pressure with exercise",

    
    "cold hands in warm room", "numbness in left arm",
    "tingling in fingers", "cold feet at night",
    "bluish nail beds", "poor circulation in legs",
    "numbness in right arm", "tingling in toes",
    "cold extremities with exercise", "pale fingers in cold",
    "poor circulation in hands", "numbness in feet",
    "tingling in hands", "cold legs at rest",
    "bluish lips with exercise", "poor circulation in feet",
    "numbness in left leg", "tingling in legs",
    "cold arms at night", "pale toes in cold",
    "poor circulation after sitting", "numbness in right leg",
    "tingling in arms", "cold fingers in summer",
    "bluish skin with activity", "poor circulation in morning",
    "numbness in hands at night", "tingling in feet at night",
    "cold toes in warm weather", "pale hands with stress",
    "poor circulation when resting", "numbness in arms at night",
    "tingling in fingers at rest", "cold feet with exercise",
    "bluish fingertips in cold", "poor circulation after standing",
    "numbness in legs at night", "tingling in toes at rest",
    "cold hands with anxiety", "pale feet with exercise",
    "poor circulation during sleep", "numbness in fingers with cold",
    "tingling in hands at night", "cold arms with stress",
    "bluish toes in winter", "poor circulation with anxiety",
    "numbness in toes with cold", "tingling in legs at night",
    "cold legs with inactivity", "pale fingers with anxiety",
    "poor circulation at night", "numbness in arms with rest",
    "tingling in fingers with stress", "cold feet with stress",
    "bluish lips at rest", "poor circulation with stress",
    "numbness in legs with rest", "tingling in toes with cold",
    "cold hands during sleep", "pale toes with anxiety",
    "poor circulation with cold", "numbness in fingers at night",
    "tingling in hands with stress", "cold arms during rest",
    "bluish skin at rest", "poor circulation during exercise",
    "numbness in toes at night", "tingling in legs with rest",
    "cold legs during sleep", "pale hands at rest",
    "poor circulation with heat", "numbness in arms with cold",
    "tingling in fingers during sleep", "cold feet during rest",
    "bluish fingertips at rest", "poor circulation with fatigue",
    "numbness in legs with cold", "tingling in toes during sleep",
    "cold hands with exercise", "pale feet at rest",
    "poor circulation with rest", "numbness in fingers with stress",
    "tingling in hands during sleep", "cold arms with cold",
    "bluish toes at rest", "poor circulation during rest",
    "numbness in toes with stress", "tingling in legs during sleep",
    "cold legs with stress", "pale fingers at rest",
    "poor circulation with exercise", "numbness in arms during sleep",
    "tingling in fingers with cold", "cold feet with cold",
    "bluish lips with stress", "poor circulation at rest",
    "numbness in legs during sleep", "tingling in toes with stress",
    "cold hands at rest", "pale toes at rest",
    "poor circulation with movement", "numbness in fingers during sleep",
    "tingling in hands with cold", "cold arms with exercise",
    "bluish skin with stress", "poor circulation with sitting",
    "numbness in toes during sleep", "tingling in legs with cold",
    "cold legs with cold", "pale hands with cold",
    "poor circulation with standing", "numbness in arms with stress",
    "tingling in fingers with exercise", "cold feet during sleep",

    
    "dizziness upon standing", "headache with high pressure",
    "vision changes with low pressure", "nausea with pressure changes",
    "fatigue with low pressure", "pressure sensitivity to salt",
    "dizziness after meals", "headache with pressure changes",
    "blurred vision with standing", "nausea with low pressure",
    "fatigue with pressure changes", "salt sensitivity symptoms",
    "dizziness with heat", "headache with low pressure",
    "vision spots with standing", "nausea with standing",
    "fatigue with standing", "pressure changes with weather",
    "dizziness with exercise", "headache with standing",
    "vision changes with exercise", "nausea with high pressure",
    "fatigue with high pressure", "pressure sensitivity to stress",
    "dizziness with stress", "headache with exercise",
    "blurred vision with exercise", "nausea with exercise",
    "fatigue with exercise", "pressure changes with diet",
    "dizziness with dehydration", "headache with dehydration",
    "vision spots with exercise", "nausea with stress",
    "fatigue with stress", "pressure sensitivity to exercise",
    "dizziness with medication", "headache with stress",
    "vision changes with stress", "nausea with dehydration",
    "fatigue with dehydration", "pressure changes with position",
    "dizziness with fasting", "headache with fasting",
    "blurred vision with stress", "nausea with medication",
    "fatigue with medication", "pressure sensitivity to position",
    "dizziness with alcohol", "headache with alcohol",
    "vision spots with stress", "nausea with fasting",
    "fatigue with fasting", "pressure changes with medication",
    "dizziness with caffeine", "headache with caffeine",
    "vision changes with medication", "nausea with alcohol",
    "fatigue with alcohol", "pressure sensitivity to heat",
    "dizziness with position change", "headache with position change",
    "blurred vision with medication", "nausea with caffeine",
    "fatigue with caffeine", "pressure changes with stress",
    "dizziness with temperature", "headache with temperature",
    "vision spots with medication", "nausea with position change",
    "fatigue with position change", "pressure sensitivity to cold",
    "dizziness with anxiety", "headache with anxiety",
    "vision changes with anxiety", "nausea with temperature",
    "fatigue with temperature", "pressure changes with anxiety",
    "dizziness with pain", "headache with pain",
    "blurred vision with anxiety", "nausea with anxiety",
    "fatigue with anxiety", "pressure sensitivity to activity",
    "dizziness with hunger", "headache with hunger",
    "vision spots with anxiety", "nausea with pain",
    "fatigue with pain", "pressure changes with pain",
    "dizziness with emotion", "headache with emotion",
    "vision changes with pain", "nausea with hunger",
    "fatigue with hunger", "pressure sensitivity to emotion",
    "dizziness with weather", "headache with weather",
    "blurred vision with pain", "nausea with emotion",
    "fatigue with emotion", "pressure changes with hunger",
    "dizziness with diet", "headache with diet",
    "vision spots with pain", "nausea with weather",
    "fatigue with weather", "pressure sensitivity to diet",
    "dizziness with activity", "headache with activity",
    "vision changes with weather", "nausea with diet",
    "fatigue with diet", "pressure changes with activity",
    "dizziness with rest", "headache with rest",
    "blurred vision with weather", "nausea with activity",
    "fatigue with activity", "pressure sensitivity to rest",
    "dizziness with sleep", "headache with sleep",
    "vision spots with weather", "nausea with rest",
    "fatigue with rest", "pressure changes with sleep",

    
    "breathlessness with stairs", "fatigue after walking",
    "chest pain during exercise", "dizziness with activity",
    "exercise intolerance morning", "weakness during workout",
    "breathlessness after meals", "fatigue with light activity",
    "chest pressure with exercise", "dizziness after exercise",
    "exercise limitation evening", "weakness after cardio",
    "breathlessness at night", "fatigue during exercise",
    "chest tightness with activity", "dizziness during workout",
    "exercise intolerance heat", "weakness with weights",
    "breathlessness with walking", "fatigue after standing",
    "chest pain after exercise", "dizziness with exertion",
    "exercise limitation morning", "weakness during sports",
    "breathlessness lying flat", "fatigue with stairs",
    "chest pressure after activity", "dizziness during cardio",
    "exercise intolerance cold", "weakness after activity",
    "breathlessness with talking", "fatigue during sports",
    "chest tightness after exercise", "dizziness with sports",
    "exercise limitation night", "weakness with exercise",
    "breathlessness carrying items", "fatigue after exercise",
    "chest pain with movement", "dizziness after sports",
    "exercise intolerance humidity", "weakness during cardio", "breathlessness bending over", "fatigue with daily tasks",
    "chest pain during sports", "dizziness with lifting",
    "exercise intolerance stress", "weakness with stairs",
    "breathlessness household tasks", "fatigue after cardio",
    "chest pressure during sports", "dizziness during training",
    "exercise limitation stress", "weakness post workout",
    "breathlessness shopping", "fatigue with housework",
    "chest tightness during sports", "dizziness after training",
    "exercise intolerance anxiety", "weakness during exercise",
    "breathlessness gardening", "fatigue with shopping",
    "chest pain climbing stairs", "dizziness with stretching",
    "exercise limitation anxiety", "weakness after running",
    "breathlessness cooking", "fatigue after housework",
    "chest pressure with stairs", "dizziness during running",
    "exercise intolerance evening", "weakness with running",
    "breathlessness cleaning", "fatigue during cleaning",
    "chest tightness with stairs", "dizziness after running",
    "exercise limitation fatigue", "weakness during training",

    
    "ankle swelling evening", "facial puffiness morning",
    "leg edema with standing", "hand swelling with heat",
    "foot swelling after exercise", "eyelid swelling morning",
    "ankle swelling right side", "facial swelling with salt",
    "leg edema after sitting", "hand swelling with activity",
    "foot swelling with shoes", "eyelid puffiness evening",
    "ankle swelling left side", "facial edema with allergies",
    "leg swelling with travel", "finger swelling with heat",
    "foot edema morning", "eye swelling with salt",
    "ankle edema with heat", "face puffiness with sleep",
    "leg swelling one sided", "hand edema morning",
    "foot swelling evening", "eyelid edema with crying",
    "ankle swelling bilateral", "facial swelling morning",
    "leg edema evening", "finger edema with salt",
    "foot swelling pregnancy", "eye puffiness allergies",
    "ankle edema exercise", "face swelling stress",
    "leg swelling heat", "hand swelling rings",
    "foot edema walking", "eyelid swelling crying",
    "ankle swelling shoes", "facial edema stress",
    "leg edema pregnancy", "finger swelling morning",
    "foot swelling socks", "eye edema allergies",
    "ankle puffiness heat", "face puffiness crying",
    "leg swelling shoes", "hand edema rings",
    "foot edema standing", "eyelid puffiness salt",
    "ankle swelling salt", "facial swelling crying",
    "leg puffiness evening", "finger edema exercise",
    "foot swelling bilateral", "eye swelling stress",
    "ankle edema sitting", "face edema morning",
    "leg swelling exercise", "hand swelling pregnancy",
    
    
    "waking with palpitations", "sleep position heart racing",
    "nighttime chest pressure", "breathing difficulty sleep",
    "nocturnal heart pounding", "waking short breath",
    "sleep disruption heartbeat", "nighttime chest pain",
    "waking with racing heart", "sleep gasping air",
    "nocturnal palpitations", "breathing problems sleep",
    "sleep position chest pain", "waking breathless",
    "nighttime heart racing", "sleep chest pressure",
    "waking with chest pain", "nocturnal breathing difficulty",
    "sleep heart pounding", "breathing trouble sleep",
    "nighttime breathlessness", "waking chest pressure",
    "sleep rapid heartbeat", "nocturnal chest pain",
    "waking heart pounding", "sleep breathing issues",
    "nighttime heart rhythm", "breathing difficulty night",
    "sleep position breathing", "waking heart racing",
    "nocturnal rapid pulse", "chest pain sleep",
    "sleep irregular heartbeat", "breathing trouble night",
    "waking irregular pulse", "nighttime heart pause",
    "sleep heart rhythm", "nocturnal breathlessness",
    "nighttime pulse changes", "breathing difficulty bed",
    "sleep heart pause", "waking pulse racing",
    "nocturnal heart rhythm", "chest pressure bed",
    "sleep pulse changes", "breathing trouble laying",
    "waking heart rhythm", "nighttime shortness breath",
    "sleep breathlessness", "nocturnal chest pressure",
    "nighttime heart changes", "breathing difficulty laying",
    "sleep heart changes", "waking chest discomfort",
    "nocturnal pulse racing", "chest pain laying",
    
    
    "standing heart racing", "bending chest pressure",
    "lying heart pounding", "position chest pain",
    "sitting pulse changes", "standing breathless",
    "bending heart racing", "lying chest pressure",
    "position heart rhythm", "sitting shortness breath",
    "standing pulse changes", "bending breathless",
    "lying heart racing", "position chest pressure",
    "sitting heart pounding", "standing chest pain",
    "bending pulse changes", "lying breathless",
    "position heart pounding", "sitting chest pressure",
    "standing heart rhythm", "bending chest pain",
    "lying pulse changes", "position breathless",
    "sitting heart racing", "standing chest pressure",
    "bending heart pounding", "lying chest pain",
    "position pulse changes", "sitting chest pain",
    "standing heart changes", "bending breathlessness",
    "lying heart rhythm", "position chest discomfort",
    "sitting pulse racing", "standing breathing difficulty",
    "bending heart rhythm", "lying chest discomfort",
    "position heart changes", "sitting breathlessness",
    "standing pulse racing", "bending chest discomfort",
    "lying heart changes", "position breathing difficulty",
    "sitting heart rhythm", "standing chest discomfort",
    "bending pulse racing", "lying breathing difficulty",
    "position heart racing", "sitting chest discomfort",
    "standing heart pounding", "bending breathing difficulty",
    "lying pulse racing", "position chest pressure",
    "sitting heart changes", "standing breathing problems",
    "bending heart changes", "lying chest pressure",     "absence seizures", "agnosia", "akathisia", "alexia", "allodynia", "amaurosis fugax",
    "amnesia", "anhedonia", "anomia", "anosmia", "aphasia", "apraxia",
    "asterixis", "ataxia", "athetosis", "aura", "autonomic dysreflexia", "bradykinesia",
    "brain fog", "cataplexy", "cerebellar gait", "chorea", "chronic nerve pain", "clonus",
    "cognitive decline", "color agnosia", "complex partial seizures", "cortical blindness", "decerebrate posturing",
    "decorticate posturing", "déjà vu", "delayed reaction time", "disequilibrium", "disorientation",
    "dissociation", "dystonia", "echolalia", "enhanced startle reflex", "facial nerve palsy",
    "facial numbness", "facial weakness", "festinating gait", "finger agnosia", "focal weakness",
    "foot drop", "forced grasping", "freezing of gait", "gait apraxia", "gait ataxia",
    "gerstmann syndrome", "glossopharyngeal neuralgia", "grand mal seizures", "grasp reflex",
    "hallucinations", "hemianopsia", "hemiballismus", "hemineglect", "hyperreflexia",
    "hypersomnia", "hypertonia", "hyporeflexia", "hypotonia", "ideomotor apraxia",
    "impaired proprioception", "impaired spatial awareness", "intention tremor", "intermittent claudication",
    "intrusive thoughts", "jacksonian march", "jargon aphasia", "kinetic tremor", "kluver-bucy syndrome",
    "lability", "lhermittes sign", "limb apraxia", "locked-in syndrome", "loss of coordination",
    "loss of deep tendon reflexes", "loss of fine motor control", "loss of gag reflex",
    "loss of position sense", "loss of temperature sensation", "loss of vibration sense",
    "meralgia paresthetica", "micrographia", "mirror movements", "monoclonal gait",
    "motor perseveration", "muscle fasciculations", "myasthenic crisis", "myoclonus",
    "narcolepsy", "nerve compression", "neuralgia", "neurogenic bladder", "neurogenic bowel",
    "neuropathic itching", "neuropathic pain", "nystagmus", "occipital neuralgia",
    "oculogyric crisis", "opsoclonus", "orthostatic hypotension", "palilalia",
    "palinopsia", "paralysis", "paresis", "paresthesia", "parkinsonian gait",
    "pathological laughter", "pathological crying", "periodic limb movements", "peripheral neuropathy",
    "phantom limb pain", "phonophobia", "photophobia", "pins and needles sensation",
    "proprioception loss", "prosopagnosia", "pseudobulbar affect", "psychomotor agitation",
    "psychomotor retardation", "ptosis", "radicular pain", "radiculopathy",
    "ramsay hunt syndrome", "restless arm syndrome", "retropulsion", "rigidity",
    "sciatica", "scotoma", "sensory ataxia", "sensory loss", "sleep paralysis",
    "sleep-wake cycle disruption", "spasticity", "spatial disorientation", "stiff person syndrome",
    "stroke-like symptoms", "sundowning", "sunset sign", "synkinesis", "taste disturbance",
    "temporal lobe symptoms", "tetany", "tic disorders", "todds paralysis", "tonic seizures",
    "torticollis", "trigeminal neuralgia", "tunnel vision", "unilateral weakness",
    "visual agnosia", "visual hallucinations", "visual neglect", "visual perseveration",
    "weakness in facial muscles", "wernickes aphasia", "alien hand syndrome", "alice in wonderland syndrome",
    "anton syndrome", "anosognosia", "auditory agnosia", "autoscopy", "balints syndrome",
    "benedikt syndrome", "brown-sequard syndrome", "capgras syndrome", "cerebellar syndrome",
    "cervical dystonia", "charles bonnet syndrome", "choreoathetosis", "cotards delusion",
    "creutzfeldt-jakob symptoms", "cryptocrystalline syndrome", "dental neuralgia",
    "diogenal apraxia", "diplopia", "dorsal midbrain syndrome", "dysarthria",
    "dysautonomia", "dyscalculia", "dysdiadochokinesia", "dysgraphia", "dyskinesia",
    "dyslexia", "dysmetria", "dyspraxia", "dystonic tremor", "eccentric fixation",
    "environmental dependency syndrome", "episodic ataxia", "executive dysfunction",
    "exploding head syndrome", "facilitory paratonia", "fahrs syndrome", "fetal akinesia",
    "finger agnosia", "flaccid paralysis", "focal dystonia", "focal seizures",
    "fovilles syndrome", "frontal lobe syndrome", "gait freezing", "gerstmanns syndrome",
    "grupal apraxia", "guillain-barre symptoms", "holmes tremor", "huntingtons symptoms",
    "hydrocephalus symptoms", "hyperekplexia", "hypergraphia", "hyperkinesia",
    "hypersexuality", "hypokinesia", "ideational apraxia", "impaired taste",
    "impaired temperature sensation", "internuclear ophthalmoplegia", "intracranial hypertension",
    "jamais vu", "kluver-bucy syndrome", "korsakoff syndrome", "lafora disease symptoms",
    "lateral medullary syndrome", "locked-in syndrome", "meige syndrome", "millard-gubler syndrome",
    "mirror-touch synesthesia", "monoplegia", "motor neuron symptoms", "multiple system atrophy symptoms",
    "muscular rigidity", "myoclonic jerks", "myokymia", "myorhythmia", "myotonia",
    "narcolepsy with cataplexy", "nerve entrapment", "neuromyotonia", "neuropathic tremor",
    "nonprogressive ataxia", "ocular dysmetria", "oculomotor apraxia", "one-and-a-half syndrome",
    "optic ataxia", "optic neuritis", "orthostatic tremor", "pallesthesia",
    "palinacousis", "palinopsia", "palmomental reflex", "paradoxical breathing",
    "paraesthesia", "paraneoplastic syndrome", "paraphasias", "paraplegia",
    "parkinsonism", "paroxysmal choreoathetosis", "pathological gambling",
    "periodic paralysis", "peripheral vertigo", "persistent vegetative state",
    "phonological dyslexia", "picrotoxin syndrome", "pisa syndrome", "pontine syndrome",
    "positive romberg sign", "postural instability", "primary writing tremor",
    "progressive supranuclear palsy", "propriospinal myoclonus", "prosopagnosia",
    "pseudoathetosis", "pseudobulbar palsy", "psychogenic seizures", "quadriparesis",
    "quadriplegia", "rapid eye movement behavior disorder", "rasmussens encephalitis symptoms",
    "reduplicative paramnesia", "reflex sympathetic dystrophy", "retinal migraine",
    "reversible ischemic neurological deficit", "rhythmic movement disorder",
    "richardsons syndrome", "rigidity", "rubral tremor", "scanning speech",
    "scintillating scotoma", "segmental dystonia", "semantic dementia", "sensory ataxia",
    "sensory epilepsy", "serotonin syndrome", "severe brain injury symptoms",
    "shy-drager syndrome", "siderosis", "simultanagnosia", "somatoparaphrenia",
    "somnolence", "spasmodic dysphonia", "spastic paraplegia", "spinal shock",
    "spinocerebellar ataxia", "status epilepticus", "stiff-person syndrome",
    "stroke symptoms", "subacute combined degeneration", "subcortical aphasia",
    "substantia nigra symptoms", "sydenhams chorea", "sylvian seizures",
    "sympathetic dystrophy", "synesthesia", "syringomyelia symptoms", "systemic neurological disease",
    "thalamic pain syndrome", "thalamic syndrome", "third nerve palsy", "tic douloureux",
    "titubation", "tonic-clonic seizures", "topographical agnosia", "tourette syndrome symptoms",
    "transient global amnesia", "transient ischemic attack symptoms", "tremor at rest",
    "trigeminal autonomic cephalalgia", "truncal ataxia", "tuberous sclerosis symptoms",
    "unilateral neglect", "upbeat nystagmus", "utilization behavior", "vascular parkinsonism",
    "vertebrobasilar insufficiency", "vestibular neuritis", "visual snow syndrome",
    "von economos disease symptoms", "wallenberg syndrome", "weber syndrome",
    "wernickes encephalopathy", "west syndrome symptoms", "wilsons disease symptoms",
    "writers cramp",     "acanthosis nigricans", "acne cysts", "acne fulminans", "acne mechanica", "acne scars",
    "acrochordon", "acrocyanosis", "actinic keratosis", "acute paronychia", "allergic contact dermatitis",
    "alopecia areata", "angular cheilitis", "anhidrosis", "atopic eruption", "atrophic skin",
    "axillary hyperpigmentation", "basal cell carcinoma signs", "beaus lines", "blanching of skin",
    "blistering sunburn", "bluish patches", "bowens disease signs", "bullous impetigo",
    "butterfly rash", "café au lait spots", "calluses", "carbuncles", "cellulitis",
    "chapped skin", "cherry angiomas", "chicken skin", "chloracne", "chromhidrosis",
    "chronic paronychia", "cirrhosis skin signs", "coal spots", "coherent skin",
    "cold panniculitis", "collodion membrane", "confluent and reticulated papillomatosis",
    "congenital melanocytic nevus", "coral bead skin", "cornification", "cradle cap",
    "cutaneous candidiasis", "cutaneous horn", "cutis marmorata", "cutis verticis gyrata",
    "cysts under skin", "dariers disease", "decubitus ulcers", "deep morphea",
    "delusions of parasitosis signs", "dermatofibroma", "dermatographism", "dermatomyositis rash",
    "dermatophytosis", "diabetic dermopathy", "diffuse hair loss", "digital mucous cyst",
    "disseminated granuloma annulare", "drug eruptions", "dry scaly patches", "dyshidrotic eczema",
    "ecthyma", "ecthyma gangrenosum", "elastosis", "ephelides", "epidermoid cyst",
    "erysipelas", "erythema ab igne", "erythema annulare centrifugum", "erythema dyschromicum perstans",
    "erythema induratum", "erythema marginatum", "erythema multiforme", "erythema nodosum",
    "erythrasma", "erythroderma", "exanthematous pustulosis", "excoriation disorder signs",
    "facial telangiectasia", "factitial dermatitis", "fibromatosis", "fixed drug eruption",
    "follicular hyperkeratosis", "folliculitis decalvans", "fordyce spots", "freckles",
    "furuncles", "gangrene", "geographic tongue", "giant cell arteritis signs",
    "gianotti-crosti syndrome", "granuloma faciale", "grovers disease", "guttate hypomelanosis",
    "guttate psoriasis", "hair collar sign", "hair shaft abnormalities", "hay fever rash",
    "heat rash", "heliotrope rash", "henoch-schönlein purpura", "hereditary hemorrhagic telangiectasia",
    "herpes gladiatorum", "hidradenitis suppurativa", "hidrotic ectodermal dysplasia",
    "hyperhidrosis", "hyperkeratosis", "hyperpigmented patches", "hypomelanosis of ito",
    "ichthyosis vulgaris", "impetigo herpetiformis", "incontinentia pigmenti", "infected hair follicles",
    "infantile acropustulosis", "infantile hemangioma", "inflammatory linear verrucous epidermal nevus",
    "ingrowing nail", "intertrigo", "irritant contact dermatitis", "jessners lymphocytic infiltrate",
    "keratoacanthoma", "keratosis pilaris", "knuckle pads", "koilonychia", "kyrle disease",
    "langers lines", "leukocytoclastic vasculitis", "lichen amyloidosis", "lichen aureus",
    "lichen nitidus", "lichen planopilaris", "lichen planus", "lichen sclerosus",
    "lichen simplex chronicus", "lichen spinulosus", "lichen striatus", "lichenoid keratosis",
    "linear iga disease", "linear morphea", "lipodystrophy", "livedo racemosa",
    "livedo reticularis", "lupus band test", "lupus pernio", "lymphangioma circumscriptum",
    "lymphomatoid papulosis", "macular amyloidosis", "madelungs disease", "maffucci syndrome",
    "majocchis granuloma", "malignant atrophic papulosis", "mastocytosis", "melasma",
    "miliaria crystallina", "miliaria profunda", "miliaria rubra", "milium",
    "molluscum contagiosum", "mondors disease", "monilethrix", "morphea",
    "mucinosis", "mycosis fungoides", "myxedema", "nail pitting",
    "necrobiosis lipoidica", "necrotizing fasciitis", "netherton syndrome", "nevus anemicus",
    "nevus comedonicus", "nevus depigmentosus", "nevus sebaceus", "nevus spilus",
    "nummular dermatitis", "onychauxis", "onychogryphosis", "onycholysis",
    "onychomadesis", "onychomatricoma", "onychomycosis", "onychorrhexis",
    "onychoschizia", "pachyonychia congenita", "palmar erythema", "palmar hyperhidrosis",
    "palmoplantar keratoderma", "panniculitis", "papular urticaria", "parakeratosis",
    "parapsoriasis", "paronychial inflammation", "pediculosis capitis", "pediculosis corporis",
    "peeling skin syndrome", "pemphigoid nodularis", "pemphigus erythematosus", "pemphigus foliaceus",
    "pemphigus vegetans", "pemphigus vulgaris", "perioral dermatitis", "peutz-jeghers syndrome",
    "photoaging", "photosensitive eruption", "phrynoderma", "pili annulati",
    "pili multigemini", "pili torti", "pilomatricoma", "pitted keratolysis",
    "pityriasis alba", "pityriasis amiantacea", "pityriasis lichenoides", "pityriasis rosea",
    "pityriasis rubra pilaris", "pityriasis versicolor", "plantar fibromatosis", "plantar hyperhidrosis",
    "poikiloderma", "polymorphic light eruption", "pompholyx", "porphyria cutanea tarda",
    "port-wine stain", "porokeratosis", "post-inflammatory hyperpigmentation", "pretibial myxedema",
    "prurigo nodularis", "prurigo pigmentosa", "pseudoacanthosis nigricans", "pseudofolliculitis barbae",
    "pseudopelade of brocq", "pseudoxanthoma elasticum", "psoriatic nail changes", "purpura annularis telangiectodes",
    "purpura fulminans", "pustular psoriasis", "pyogenic granuloma", "pyoderma faciale",
    "pyoderma gangrenosum", "radiodermatitis", "raynauds phenomenon", "reactive perforating collagenosis",
    "recurrent cutaneous eczema", "relapsing polychondritis", "rheumatoid nodules", "rhinophyma",
    "rosacea fulminans", "rothmund-thomson syndrome", "rubinstein-taybi syndrome", "sarcoidosis",
    "scalp folliculitis", "scarlet fever rash", "scleredema", "scleroderma",
    "sebaceous adenoma", "sebaceous hyperplasia", "seborrheic keratosis", "segmental neurofibromatosis",
    "senile purpura", "serpiginous skin lesion", "sheepskin erosion", "shin spots",
    "shingles", "silvery hair syndrome", "skin dimpling", "skin induration",
    "skin laxity", "skin plaques", "skin tags", "small vessel vasculitis",
    "solar elastosis", "solar keratosis", "solar lentigines", "solar purpura",
    "speckled hyperpigmentation", "speckled hypopigmentation", "spider angioma", "spiradenoma",
    "sporotrichosis", "staphylococcal scalded skin", "stasis dermatitis", "striae distensae",
    "subacute cutaneous lupus", "subcorneal pustular dermatosis", "subcutaneous emphysema", "subcutaneous nodules",
    "sweets syndrome", "symmetrical drug-related intertriginous flexural exanthema", "syringoma",
    "systemic contact dermatitis", "targetoid hemosiderotic hemangioma", "telangiectasia macularis eruptiva perstans",
    "terra firma-forme dermatosis", "textile contact dermatitis", "thermal burn", "tinea capitis",
    "tinea corporis", "tinea cruris", "tinea faciei", "tinea incognito",
    "tinea manuum", "tinea nigra", "tinea pedis", "tinea versicolor",
    "toxic epidermal necrolysis", "traumatic purpura", "trichilemmal cyst", "trichomycosis axillaris",
    "trichostasis spinulosa", "trichotillomania signs", "tufted folliculitis", "tungiasis",
    "urticaria pigmentosa", "urticarial vasculitis", "ustekinumab-induced acne", "vaccination site reaction",
    "vanishing bone disease", "varicella", "vascular ectasia", "vasculopathic purpura",
    "venous lake", "verruca plana", "verruca vulgaris", "viral exanthem",
    "vitiligo", "waxy skin", "weather-beaten skin", "weeping eczema",
    "werner syndrome", "wise lines", "wooly hair nevus", "xanthelasma",
    "xanthoma disseminatum", "xanthoma eruptivum", "xerosis cutis", "yellow nail syndrome",
    "zinc deficiency dermatitis", "zosteriform lichen planus", "zosteriform speckled lentiginous nevus",     "brain fog", "word-finding difficulty", "decreased attention span", "poor concentration",
    "spatial disorientation", "temporary memory lapses", "mental exhaustion",
    "difficulty with calculations", "reduced cognitive speed", "mental fatigue",
    "thought processing delays", "difficulty multitasking", "poor mental stamina",
    "cognitive overwhelm", "mental cloudiness", "difficulty planning",
    "impaired decision making", "slower thinking", "reduced mental clarity",
    "cognitive strain", "mental sluggishness", "decreased alertness",

    
    "sleep paralysis", "sleep talking", "teeth grinding during sleep",
    "excessive dreaming", "interrupted sleep patterns", "early morning awakening",
    "difficulty falling back asleep", "restless sleeping", "sleep walking",
    "morning grogginess", "daytime drowsiness", "microsleep episodes",
    "reversed sleep cycle", "irregular sleep schedule", "sleep rhythm disturbances",
    "difficulty waking up", "sleep maintenance issues", "poor sleep quality",

    
    "temperature fluctuations", "cold sweats", "internal chills",
    "localized warmth", "temperature sensitivity", "heat intolerance",
    "cold intolerance", "paradoxical sweating", "night chills",
    "afternoon fever spikes", "morning temperature changes", "evening temperature changes",
    "hot flushes", "cold spells", "thermal dysregulation",

    
    "post-exertional malaise", "afternoon energy crashes", "morning fatigue",
    "energy fluctuations", "reduced stamina", "exercise intolerance",
    "delayed fatigue onset", "energy depletion", "activity intolerance",
    "reduced physical endurance", "post-activity exhaustion", "energy level variations",
    "sudden energy drops", "delayed recovery after activity", "reduced physical capacity",

    
    "morning joint stiffness", "evening joint pain", "muscle fasciculations",
    "muscle tension headaches", "joint clicking", "muscle knots",
    "trigger points", "muscle hardening", "joint popping",
    "muscle twitching at rest", "exercise-induced pain", "delayed onset muscle soreness",
    "joint instability", "muscle weakness after exercise", "joint looseness",

    
    "skin temperature changes", "localized skin warming", "patchy skin coloring",
    "skin sensitivity to pressure", "altered skin sensation", "skin crawling sensation",
    "burning skin patches", "skin temperature fluctuations", "skin hypersensitivity",
    "localized skin cooling", "skin texture changes", "skin tenderness",

    
    "postural blood pressure changes", "position-related dizziness", "exercise-induced palpitations",
    "irregular pulse patterns", "blood pressure fluctuations", "circulation changes",
    "positional heart rate changes", "exercise intolerance", "circulation problems",
    "blood pressure variations", "pulse irregularities", "heart rhythm changes",

    
    "exercise-induced breathlessness", "positional breathing changes", "breathing pattern disruption",
    "breath holding episodes", "irregular breathing patterns", "air hunger",
    "shallow breathing episodes", "breathing difficulty at rest", "respiratory pattern changes",
    "breathing rhythm irregularities", "breathing coordination problems", "breathing pattern variations",

    
    "post-prandial bloating", "early satiety", "delayed gastric emptying",
    "food intolerance symptoms", "meal-related discomfort", "digestive timing changes",
    "appetite fluctuations", "digestive rhythm changes", "food sensitivity reactions",
    "variable bowel habits", "digestive pattern changes", "meal tolerance variations",

    
    "coordination difficulties", "balance problems when turning", "gait uncertainties",
    "movement hesitation", "reduced spatial awareness", "position sense alterations",
    "movement planning difficulties", "balance control issues", "coordination changes",
    "movement precision problems", "spatial orientation issues", "balance adjustment problems",

    
    "heightened sound sensitivity", "light pattern sensitivity", "touch sensitivity changes",
    "altered taste perception", "smell sensitivity", "sensory processing changes",
    "environmental sensitivity", "sensory overload", "texture sensitivity",
    "temperature perception changes", "sensory integration issues", "sensory processing variations",

    
    "blood sugar fluctuations", "metabolism changes", "hormone-related symptoms",
    "thyroid function variations", "cortisol level changes", "metabolic rate fluctuations",
    "endocrine system changes", "hormone balance issues", "metabolic pattern changes",
    "blood sugar regulation issues", "hormone rhythm disruptions", "metabolic fluctuations",

    
    "generalized malaise", "reduced overall function", "systemic inflammation signs",
    "constitutional symptom patterns", "general health changes", "systemic reactions",
    "whole-body responses", "general wellness changes", "constitutional variations",
    "system-wide symptoms", "general health fluctuations", "constitutional changes",

    
    "movement initiation difficulty", "reduced movement speed", "altered movement patterns",
    "movement hesitation", "reduced movement fluidity", "movement coordination changes",
    "movement planning issues", "movement timing problems", "movement pattern variations",
    "movement sequence difficulties", "movement control issues", "movement rhythm changes",

    
    "autonomic dysfunction signs", "vasomotor changes", "autonomic regulation issues",
    "temperature control problems", "autonomic balance changes", "regulatory system variations",
    "autonomic response changes", "system regulation issues", "autonomic pattern changes",
    "regulatory function problems", "autonomic system variations", "regulatory pattern changes",

    
    "morning symptom patterns", "afternoon symptom changes", "evening symptom variations",
    "cyclic symptom patterns", "diurnal symptom changes", "symptom timing variations",
    "periodic symptom patterns", "temporal symptom changes", "symptom cycle variations",
    "symptom pattern timing", "symptom occurrence patterns", "temporal variation patterns",

    
    "stress response changes", "exercise response patterns", "recovery pattern changes",
    "activity response variations", "physical adaptation changes", "response pattern variations",
    "physical reaction changes", "adaptation pattern issues", "response timing changes",
    "physical adjustment patterns", "response variation issues", "adaptation timing changes",

    
    "emotional lability", "mood pattern changes", "emotional regulation issues",
    "mood stability changes", "emotional response patterns", "mood variation issues",
    "emotional control changes", "mood regulation problems", "emotional pattern changes",
    "mood control issues", "emotional stability changes", "mood response variations",

    
    "delayed recovery patterns", "healing time changes", "recovery process variations",
    "healing pattern changes", "recovery rate variations", "healing response changes",
    "recovery timing issues", "healing process changes", "recovery pattern variations",
    "healing rate changes", "recovery response issues", "healing timing variations",

    
    "system coordination issues", "integration pattern changes", "systemic response variations",
    "coordination pattern changes", "system response issues", "integration timing changes",
    "systemic pattern variations", "coordination timing issues", "system integration changes",
    "response pattern variations", "integration process changes", "systemic timing issues",

    
    "adaptation pattern changes", "response timing variations", "adjustment pattern issues",
    "adaptation timing changes", "response pattern variations", "adjustment timing issues",
    "adaptation process changes", "response variation patterns", "adjustment process changes",
    "adaptation rate variations", "response process changes", "adjustment rate variations",

    
    "weather sensitivity patterns", "environmental reaction changes", "climate response variations",
    "seasonal pattern changes", "environmental adaptation issues", "weather response patterns",
    "climate adaptation changes", "seasonal response variations", "environmental pattern changes",
    "weather adaptation issues", "climate pattern variations", "seasonal adaptation changes",

    
    "compensatory movement patterns", "adaptation strategy changes", "compensation mechanism variations",
    "compensatory pattern changes", "adaptation mechanism issues", "compensation strategy variations",
    "compensatory response changes", "adaptation pattern variations", "compensation timing changes",
    "compensatory timing issues", "adaptation timing variations", "compensation process changes",

    
    "functional capacity changes", "performance pattern variations", "functional ability changes",
    "performance timing issues", "functional pattern variations", "performance ability changes",
    "functional timing issues", "performance process changes", "functional process variations",
    "performance rate changes", "functional rate variations", "performance pattern changes",

    
    "stress adaptation patterns", "stress response variations", "stress recovery changes",
    "stress pattern variations", "stress timing issues", "stress adaptation changes",
    "stress recovery patterns", "stress process variations", "stress timing changes",
    "stress adaptation issues", "stress response patterns", "stress recovery variations",

    
    "systemic response patterns", "system adaptation changes", "systemic process variations",
    "system pattern changes", "systemic timing issues", "system process variations",
    "systemic adaptation patterns", "system timing changes", "systemic pattern variations",
    "system response patterns", "systemic timing variations", "system adaptation issues",

    
    "pattern timing changes", "response variation issues", "pattern process changes",
    "response timing variations", "pattern adaptation issues", "response process changes",
    "pattern variation issues", "response adaptation changes", "pattern timing variations",
    "response pattern changes", "pattern process variations", "response timing issues",

    
    "integration timing changes", "coordination process variations", "integration pattern changes",
    "coordination timing issues", "integration process variations", "coordination pattern changes",
    "integration response patterns", "coordination variation issues", "integration timing issues",
    "coordination response patterns", "integration process changes", "coordination timing variations",

    
    "recovery timing changes", "healing process variations", "recovery pattern changes",
    "healing timing issues", "recovery process variations", "healing pattern changes",
    "recovery response patterns", "healing variation issues", "recovery timing issues",
    "healing response patterns", "recovery process changes", "healing timing variations", "itchy skin"
],


    treatment: [
      "chemotherapy", "radiotherapy", "immunotherapy", "physical therapy", "occupational therapy",
      "cognitive behavioral therapy", "psychotherapy", "speech therapy", "hormone therapy", "gene therapy",
      "dialysis", "stem cell treatment", "acupuncture", "chiropractic", "massage therapy",  
      "hydrotherapy", "oxygen therapy", "light therapy", "heat therapy", "cold therapy",
      "insulin therapy", "antibiotic treatment", "antiviral therapy", "pain management", "wound care",
      "respiratory therapy", "nutritional therapy", "exercise therapy", "manual therapy", "electroconvulsive therapy",
      "hyperbaric oxygen therapy", "radiation therapy", "laser therapy", "ultrasound therapy", "shock wave therapy",
      "aromatherapy", "art therapy", "music therapy", "play therapy", "behavioral therapy",
      "family therapy", "group therapy", "exposure therapy", "dialectical therapy", "cognitive therapy",
      "mindfulness therapy", "interpersonal therapy", "psychodynamic therapy", "supportive therapy", "narrative therapy",
      "solution-focused therapy", "reality therapy", "gestalt therapy", "animal therapy", "wilderness therapy",
      "dance therapy", "drama therapy", "recreational therapy", "vocational therapy", "rehabilitation",
      "orthopedic therapy", "neurological therapy", "cardiac rehab", "pulmonary rehab", "vestibular rehab",
      "vision therapy", "voice therapy", "swallowing therapy", "balance therapy", "gait training",
      "mobility training", "strength training", "flexibility training", "endurance training", "coordination training",
      "oral therapy", "intravenous therapy", "topical treatment", "intradermal therapy", "subcutaneous therapy",
      "intramuscular therapy", "epidural treatment", "spinal therapy", "joint therapy", "bone therapy",
      "tissue therapy", "organ therapy", "systemic therapy", "targeted therapy", "combination therapy",
      "maintenance therapy", "preventive therapy", "palliative therapy", "curative therapy", "supportive care",
      "emergency treatment", "intensive care", "critical care", "acute care", "long-term care",
      "home care", "hospice care", "respite care", "transitional care", "primary care",
      "specialty care", "alternative medicine", "complementary therapy", "holistic treatment", "natural remedies",
      "herbal therapy", "homeopathic treatment", "naturopathic therapy", "traditional medicine", "integrative medicine",
      "conventional therapy", "experimental treatment", "investigational therapy", "clinical trial", "research protocol",
      "standard treatment", "first-line therapy", "second-line therapy", "salvage therapy", "consolidation therapy",
      "induction therapy", "adjuvant therapy", "neoadjuvant therapy", "concurrent therapy", "sequential therapy",
      "intermittent therapy", "continuous therapy", "pulse therapy", "dose-dense therapy", "metronomic therapy",
      "empiric therapy", "definitive therapy", "conservative treatment", "aggressive treatment", "radical therapy",
      "minimal therapy", "maximal therapy", "optimal therapy", "suboptimal therapy", "alternative therapy",
      "backup therapy", "rescue therapy", "bridge therapy", "temporary treatment", "permanent treatment",
      "outpatient treatment", "inpatient treatment", "day therapy", "night therapy", "weekend therapy",
      "breakthrough therapy", "innovative therapy", "novel treatment", "established therapy", "proven treatment",
      "unproven therapy", "controversial therapy", "accepted treatment", "recommended therapy", "prescribed treatment",
      "self-administered therapy", "supervised treatment", "monitored therapy", "controlled therapy", "regulated treatment",
      "standardized therapy", "individualized treatment", "personalized therapy", "customized treatment",
      "broad-spectrum therapy", "narrow-spectrum therapy", "specific treatment", "non-specific therapy",
      "local treatment", "regional therapy", "systemic treatment", "whole-body therapy", "partial treatment",
      "complete therapy", "incomplete treatment", "interrupted therapy", "discontinued treatment", "resumed therapy",
      "modified treatment", "adjusted therapy", "escalated treatment", "de-escalated therapy", "augmented treatment",
      "single-agent therapy", "multi-agent treatment", "dual therapy", "triple therapy", "quadruple treatment",
      "rotational treatment", "cyclical therapy", "periodic treatment", "staged treatment", "phased therapy",
      "stepped treatment", "tiered therapy", "layered treatment", "primary therapy", "secondary treatment",
      "tertiary therapy", "quaternary treatment", "supplementary therapy", "complementary treatment", "adjunctive therapy",
      "supportive treatment", "symptomatic therapy", "prophylactic treatment", "preventive therapy", "therapeutic treatment",
      "remedial therapy", "corrective treatment", "restorative therapy", "rehabilitative treatment", "stabilizing treatment"
    ],

    
        diagnosis: [
          "blood test", "urine test", "imaging", "x-ray", "CT scan", "MRI", "ultrasound",
          "biopsy", "colonoscopy", "endoscopy", "mammogram", "pap smear", "physical examination",
          "mental status exam", "neurological exam", "cardiac exam", "pulmonary function test",
          "stress test", "genetic testing", "allergy testing", "hormone testing", "culture test",
          "antibody test", "PCR test", "rapid test", "screening", "diagnostic imaging",
          "pathology report", "lab results", "diagnostic criteria", "differential diagnosis",
          "preliminary findings", "confirmatory test", "diagnostic assessment", "clinical evaluation",
          "genetic screening", "serology", "cytology", "radiology", "electrocardiogram (ECG)", 
          "echocardiogram", "electroencephalogram (EEG)", "sleep study", "angiography", "laparoscopy",
          "thoracentesis", "paracentesis", "bone marrow biopsy", "skin biopsy", "liver biopsy", "kidney biopsy",
          "arterial blood gas (ABG)", "electromyography (EMG)", "nerve conduction study", "sputum culture",
          "fecal occult blood test", "nasal endoscopy", "lumbar puncture (spinal tap)", "serum test",
          "lumbar puncture", "urinary cytology", "video fluoroscopic swallow study", "sweat test", "spinal imaging",
          "chest X-ray", "abdominal ultrasound", "pelvic ultrasound", "brain scan", "CT angiography",
          "breast ultrasound", "radiographic contrast", "CT-guided biopsy", "colorectal cancer screening",
          "magnetic resonance angiography (MRA)", "cardiac MRI", "endoscopic ultrasound", "direct laryngoscopy",
          "bronchoscopy", "barium swallow", "barium enema", "cardiac catheterization", "coronary angiography",
          "electrolyte panel", "renal function test", "complete blood count (CBC)", "liver function test",
          "lipid profile", "thyroid function test", "serum creatinine", "blood urea nitrogen (BUN)",
          "prostate-specific antigen (PSA)", "high-sensitivity C-reactive protein (hs-CRP)", "blood glucose test",
          "urinary analysis", "complete metabolic panel", "ABG analysis", "hemoglobin A1c", "urinary protein",
          "urinary specific gravity", "urinary pH", "Cystatin C test", "serum albumin", "hepatitis test",
          "HIV test", "tuberculosis test", "syphilis test", "hepatitis C test", "gonorrhea test", "chlamydia test",
          "HPV test", "COVID-19 test", "pediatric screening", "eye examination", "visual acuity test", "fundoscopy",
          "refraction test", "pressure test", "slit-lamp examination", "ophthalmic imaging", "retinal scan",
          "optical coherence tomography (OCT)", "autoimmune screening", "chest CT scan", "high-resolution CT scan",
          "PET scan", "FDG-PET scan", "single-photon emission computed tomography (SPECT)", "functional MRI",
          "diffusion tensor imaging (DTI)", "SPECT-CT", "gastrointestinal endoscopy", "gastroscopy", "sigmoidoscopy",
          "duodenal biopsy", "small bowel biopsy", "rectal biopsy", "bronchial lavage", "stool culture", 
          "blood smear", "vaginal examination", "urethral swab", "lung biopsy", "chest ultrasound", "EEG recording",
          "hearing test", "audiometry", "tinnitus test", "laryngeal swab", "proctoscopy", "colposcopy", "rectal exam",
          "surgical biopsy", "lung function test", "serum iron level", "mucus culture", "cystoscopy", "spinal MRI",
          "cardiopulmonary exercise testing", "nasopharyngoscopy", "clinical trial", "pathological staging",
          "CT colonography", "clinical neurophysiological testing", "blood culture", "chronic disease screening",
          "therapeutic drug monitoring", "electrolyte imbalance test", "HLA typing", "genome sequencing", "forensic autopsy",
          "plasma protein test", "hemoglobin electrophoresis", "autoantibody test", "DNA testing", "syndrome diagnosis",
          "neuromuscular test", "blood pressure monitoring", "cardiac stress test", "echocardiographic stress testing",
          "cardiac CT scan", "troponin test", "pregnancy test", "urinary culture", "serum protein electrophoresis",
          "CD4 count", "immunoglobulin test", "serum ferritin", "serum potassium level", "brain biopsy", "mental health assessment",
          "muscle biopsy", "genetic counseling", "fecal transplant", "urinary flow test", "nasal swab",
          "virus culture", "enteric stool culture", "sputum test", "infection test", "serum calcium level",
          "sweat chloride test", "molecular test", "diagnostic laparoscopy", "pupil reaction test", "cranial nerve exam",
          "physical therapy assessment", "neurological screening", "urinary analysis for drugs", "breathing test",
          "cardiovascular exam", "tumor marker test", "bioelectrical impedance analysis (BIA)", "hip X-ray", "axial CT scan",
          "digital rectal exam (DRE)", "apnea test", "saliva test", "glucose tolerance test", "longitudinal study",
          "hip ultrasound", "synovial fluid analysis", "carotid artery ultrasound", "toxicity screening", "endocrine evaluation",
          "vertebral imaging", "bone density test", "ecchymosis test", "chronic disease evaluation", "cognitive function test",
          "urine dipstick", "hearing screening", "lipid panel", "lymph node biopsy", "cyst examination", "thoracic imaging",
          "cervical imaging", "chest fluoroscopy", "cerebral angiogram", "tumor biopsy", "spinal fluid analysis",
          "urethral ultrasound", "colorectal screening", "dental x-ray", "urethral function test", "Liver elastography",
          "surgical procedure evaluation", "pre-surgical evaluation", "medical imaging", "lymphocyte subset test",
          "pregnancy ultrasound", "skeletal survey", "abdominal CT scan", "cerebral MRI", "clinical trial testing",
          "genomic test", "viral load test", "biomarker testing", "blood clotting test", "blood gas analysis", 
          "intravenous pyelogram (IVP)", "salivary gland biopsy", "vestibular testing", "chromosomal analysis",
          "viral culture test", "patch test", "liver function screen", "peripheral nerve conduction study", 
          "thermography", "electronic health record (EHR) review", "cardiac rhythm test", "coronary artery calcium score",
          "serum lactate level", "immunofixation electrophoresis", "dynamic ultrasound", "cognitive behavioral therapy assessment"
        ],
      
      
     
        
            prognosis: [
              "favorable", "poor", "good", "recovery", "chronic", "terminal", "life expectancy", "survival", "mortality",
              "recurrence", "complication", "progression", "remission", "response", "timeline", "rehabilitation", "functional",
              "quality", "long-term", "short-term", "cure", "management", "follow-up", "remission", "therapy", "resilience",
              "improvement", "residual", "deterioration", "worsening", "gradual", "intervention", "spontaneous", "stabilization",
              "plateau", "recovery", "mental health", "psychological", "rehabilitative", "adaptive", "restoration", "efficacy",
              "success", "relief", "control", "side effects", "effectiveness", "well-being", "independence", "adherence", "risk",
              "metastasis", "prevention", "markers", "multimodal", "prediction", "capacity", "decline", "wellness", "monitoring",
              "prediction", "cancer", "non-cancer", "progressive", "palliative", "resolution", "stability", "severity", "optimization",
              "failure", "early-stage", "advanced", "advanced disease", "resolution", "residual", "network", "adherence", "recovery",
              "compliance", "self-care", "decline", "progression", "flare-up", "monitoring", "modification", "impact", "disease",
              "intervention", "hospitalization", "complication", "response", "failure", "failure risk", "optimization", "prediction",
              "management", "improvement", "impact", "non-cancerous", "relapse", "immunotherapy", "radiation", "chemotherapy", "surgery",
              "mental", "physical", "rehabilitation", "response", "failure", "counseling", "uncertainty", "likelihood", "early",
              "condition", "health", "progression-free", "accuracy", "stabilization", "prolonged", "recovery", "recovery", "mortality",
              "outcomes", "care", "genetic", "genetic", "cognitive", "intervention", "care", "prolonged", "success", "improvement", "success",
              "therapy", "non-invasive", "outlook", "comprehensive", "monitoring", "adjustment", "comorbidity", "long-term", "specialist",
              "evolution", "survival", "expectancy", "personal", "recovery", "rate", "disease", "prevention", "management", "outcome",
              "care", "resource", "resolution", "quality", "timing", "outlook", "period", "fatal", "terminal", "fate", "life-cycle", "burden",
              "life expectancy", "expectancy", "remission", "progressive", "prevention", "outcome", "success", "side-effect", "chronicity",
              "treatment", "recovery", "screening", "pain", "aging", "diagnosis", "track", "improvement", "markers", "metabolic", "sequelae",
              "asymptomatic", "self-management", "medication", "incidence", "epigenetic", "progression", "health", "mental", "correction",
              "management", "adjustment", "change", "restoration", "growth", "recovery", "function", "adaptation", "adaptation", "self-care",
              "readmission", "hospital", "emergency", "support", "progression-free", "intervention", "change", "calculation", "response",
              "reduction", "healthcare", "long-term", "assessment", "tracking", "state", "healthcare", "implementation", "testing",
              "impact", "improvement", "monitoring", "tracking", "evaluation", "family", "support", "resilience", "continuation", "outcome",
              "delay", "evaluation", "care", "relapse", "initial", "care", "increase", "maintenance", "prevention", "objective", "monitor",
              "symptoms", "response", "severity", "recovery", "stability", "diagnostic", "pain-relief", "alleviation", "adherence", "injury",
              "screening", "disease-free", "improvement", "disease-specific", "intervention", "progression-free", "decline", "preservation",
              "symptom-free", "restoration", "healing", "recovery", "supportive", "critical", "age", "health", "self", "prolonged",
              "monitoring", "supportive", "decrease", "end-stage", "impairment", "treatment-related", "life-quality", "rehabilitation",
              "recovery", "patient", "chronic", "post-op", "long-term", "function", "medication", "palliative", "lifestyle", "personal",
              "therapeutic", "deterioration", "monitoring", "post-surgery", "adjustment", "mental", "intervention", "stabilization", "response",
              "change", "trajectory", "interventions", "care", "restorative", "impact", "enhancement", "care", "remedy", "evaluation"
            ],
          
          
     
            
                history: [
                  "medical", "family", "surgical", "medication", "allergy", "vaccination", "social", "travel", "occupational", 
                  "psychiatric", "obstetric", "developmental", "trauma", "lifestyle", "genetic", "immunization", "illnesses", "surgeries", 
                  "conditions", "symptoms", "treatments", "hospitalizations", "emergency", "consultations", "screenings", "procedures", 
                  "radiology", "pathology", "blood", "allergies", "status", "use", "infections", "mental", "substance", "tobacco", "alcohol", 
                  "drugs", "interactions", "sleep", "exercise", "diet", "stress", "pain", "family", "autoimmune", "infectious", "cancer", 
                  "cardiovascular", "respiratory", "neurological", "diabetes", "obesity", "gastrointestinal", "endocrine", "skin", "vascular", 
                  "renal", "urological", "gynecological", "reproductive", "pregnancy", "menstrual", "infertility", "complications", "prenatal", 
                  "psychiatric", "stroke", "seizures", "cognitive", "HIV", "hepatitis", "fatigue", "surgery", "hospital", "rehabilitation", 
                  "physical", "occupational", "speech", "diagnostics", "radiology", "laboratory", "evaluations", "assessments", "studies", 
                  "complications", "admissions", "visits", "outpatient", "therapy", "homeopathy", "herbal", "abuse", "accidents", "fractures", 
                  "musculoskeletal", "errors", "malpractice", "support", "caregiver", "transportation", "housing", "environmental", "toxins", 
                  "radiation", "pesticides", "chemicals", "hazards", "allergies", "workplace", "military", "combat", "disability", "needs", 
                  "insurance", "expenses", "access", "adherence", "compliance", "socioeconomic", "cultural", "religious", "literacy", 
                  "education", "resources", "alcohol", "smoking", "STIs", "contraception", "menopause", "postpartum", "planning", "pediatrics", 
                  "vaccines", "childhood", "growth", "milestones", "social", "adverse", "experiences", "resilience", "safety", "bullying", 
                  "trauma", "support", "interventions", "plan"
                ]
              
              
   };
  
  
   export const analyzeTopics = (text) => {
    const words = text.toLowerCase().split(/\s+/);
    const totalWords = words.length;
    
    return Object.entries(topicPatterns).reduce((results, [topic, patterns]) => {
      const matches = words.filter(word => patterns.includes(word));
      results[topic] = {
        count: matches.length,
        percentage: (matches.length / totalWords) * 100
      };
      return results;
    }, {});
  };