export const SENTIMENT_WORDS = {
    positive: [
        'improvement', 'stable', 'responsive', 'effective', 'successful', 
        'progress', 'recovery', 'enhanced', 'well', 'outcome', 
        'favorable', 'better', 'managed', 'positive response', 'optimistic',
        'healing', 'resolved', 'functional', 'regression-free', 'normal', 
        'clear', 'balanced', 'treated', 'restored', 'regained', 'advancing',
        'strengthened', 'reinforced', 'beneficial', 'resilient', 'improving',
        'thriving', 'energized', 'revitalized', 'rejuvenated', 'recovered',
        'rebuilt', 'restored health', 'on track', 'functional capacity', 
        'good prognosis', 'progressing', 'well-being', 'rising', 'consistent',
        'enduring', 'sustained', 'sound', 'firm', 'confirmed', 'steadfast',
        'adaptive', 'stable condition', 'reduced risk', 'smooth recovery', 
        'reliable', 'clear response', 're-established', 'maintained', 
        'long-lasting', 'long-term improvement', 'balanced outcome', 'beneficial outcome',
        'healthy', 'improved health', 'elevated', 'resilient recovery', 'stronger',
        'optimal', 'minimal side effects', 'renewed', 'recovering well', 
        'smoothly progressing', 'functioning well', 'manageable', 'restored function',
        'well-managed', 'incremental progress', 'minimal complications', 'no setbacks',
        'rejuvenation', 'overcoming', 'long-term stability', 'steady improvement',
        'postive signs', 'manageable condition', 'substantial improvement', 
        'increased functionality', 'optimal recovery', 'lessened symptoms', 'recovery-driven',
        'boosted', 'profound improvement', 'boosted strength', 'enhanced stability', 
        'enhanced mobility', 'working well', 'responding well', 'healing process',
        'well-received treatment', 'restored abilities', 'positive shift', 
        'enhanced condition', 'stable recovery', 'improved prognosis', 
        'consistent improvements', 'sustained health', 'positive trajectory',
        'resilience', 'improvement milestone', 'substantial progress', 
        'more alert', 'functionally enhanced', 'rising strength', 'vital recovery',
        'greater stability', 'improved response', 'encouraging signs', 
        'steadfast health', 'overcoming difficulties', 'positive trends', 
        're-energized', 'optimally progressing', 'improved strength', 'positive shift',
        'significant progress', 'recovered well', 'greater endurance', 
        'full recovery', 'optimizing function', 'positive health status', 
        'no further complications', 'effective treatment', 'steady recovery', 
        'health improvement', 'symptom-free', 'resolved issue', 'increased vitality',
        'eliminating symptoms', 'growing strength', 'enhanced well-being', 'total recovery',
        'successful outcome', 'clear of symptoms', 'optimal health', 'thriving health',
        'significant gain', 'well-coordinated treatment', 'sustained wellness', 
        'improved function', 'advanced health', 'system recovery', 'restoration of health',
        'vibrant recovery', 'stable progress', 'positive development', 
        'increased health status', 'moving forward', 'no evidence of deterioration', 
        'improvement in health', 'positive treatment outcome', 'better quality of life', 
        'continuous improvement', 'well-handled situation', 'advancing treatment plan', 
        'symptoms under control', 'positive medical outcomes', 'strengthening health',
        'increased mobility', 'better health condition', 'recovering without complications',
        'positive outlook', 'symptoms under management', 'increasing functionality', 
        'progressive health', 'increasing strength', 'decreasing severity', 
        'gradual improvement', 'strengthened health', 'optimal rehabilitation', 
        'overall recovery', 'clear recovery path', 'gradual restoration', 'improving quality of life',
        'successful intervention', 'steady improvement process', 'reduced burden', 
        'positive progression', 'no complications', 'improved performance', 
        'good clinical outcome', 'stable vital signs', 'favorable clinical response',
        'enhanced healing', 'positive health change', 'restored capacity', 'clear progress',
        'improved functionality', 'no new issues', 'advancing recovery', 'moving toward resolution',
        'higher energy', 'clear treatment effects', 'healthier state', 'overall progress',         'hopeful', 'relieved', 'optimistic', 'comforted', 'encouraged', 
        'satisfied', 'content', 'calm', 'assured', 'peaceful', 
        'reassured', 'uplifted', 'confident', 'empowered', 'positive',
        'joyful', 'delighted', 'cheerful', 'grateful', 'motivated', 
        'inspired', 'enthusiastic', 'pleased', 'at ease', 'relaxed', 
        'contented', 'happy', 'elated', 'excited', 'blessed', 
        'thankful', 'hopeful outlook', 'grateful heart', 'peaceful state', 
        'joyous', 'thrilled', 'fulfilled', 'lighthearted', 'cheerful mood',
        'in good spirits', 'sociable', 'optimistic outlook', 'well-being', 
        'lively', 'refreshed', 'energized', 'relaxed state', 'free of worry', 
        'grinning', 'smiling', 'jubilant', 'positive vibes', 'heartfelt joy', 
        'relaxed mind', 'eager', 'enthusiastically', 'exuberant', 'elated mood', 
        'calm heart', 'joy-filled', 'rejuvenated', 'open-minded', 'peaceful mind', 
        'celebratory', 'grateful attitude', 'eager to improve', 'appreciative', 
        'sociable mood', 'at peace', 'good-natured', 'happy-go-lucky', 
        'joyous heart', 'contented heart', 'enlightened', 'pleased demeanor', 
        'blissful', 'uplifted spirit', 'refreshed mind', 'satisfied heart', 
        'positively engaged', 'favorable', 'relaxing', 'relaxed spirit', 
        'optimistic state', 'renewed', 'hopeful mindset', 'recovered', 
        'well-contented', 'spirit-lifting', 'happy-hearted', 'radiant', 
        'brightened', 'thankful spirit', 'glowing', 'hopeful soul', 'good-humored', 
        'restored', 'rested', 'in a good place', 'gleaming', 'light-spirited', 
        'joyous spirit', 'contentment', 'thriving', 'radiant smile', 
        'enthusiastic outlook', 'loving', 'welcoming', 'excited for progress', 
        'peaceful outlook', 'relaxed body', 'lively spirit', 'smiling heart', 
        'brightened mood', 'cheery', 'glowing heart', 'bright future', 
        'cheerful disposition', 'heartwarming', 'rejuvenated spirit', 'motivated mind', 
        'blessed heart', 'gratefully accepting', 'rejoicing', 'content and relaxed', 
        'inspired heart', 'empowered mind', 'heartened', 'healing', 'elated heart', 
        'excited progress', 'feeling good', 'new hope', 'empowered state', 
        'enthusiastically hopeful', 'good-energy', 'impressed', 'refreshed outlook', 
        'happy feeling', 'blessed outlook', 'cheerful face', 'high-spirited', 
        'optimistic attitude', 'recovered spirit', 'calm demeanor', 'in high spirits', 
        'well-rested', 'joyful state', 'blissful mood', 'thankful outlook', 
        'heartfelt optimism', 'free of stress', 'hopeful journey', 'beaming', 
        'thankful spirit', 'improvement noted', 'optimistic change', 'unworried', 
        'relieved joy', 'content state', 'relaxed atmosphere', 'alive with hope', 
        'soothing', 'clear-headed', 'lightened mood', 'feeling hopeful', 
        'full of promise', 'hopeful energy', 'satisfied heart', 'renewing', 
        'feeling great', 'bright mind', 'feeling reassured', 'supportive', 
        'enthusiastic spirit', 'open-hearted', 'hopeful anticipation', 'rejuvenated outlook', 
        'feeling empowered', 'gratefully optimistic', 'happily engaged', 
        'cheerful anticipation', 'optimism rising', 'delightful', 'gleeful', 
        'well-supported', 'optimistically engaged', 'enthusiastically optimistic', 
        'gratefully hopeful', 'hopeful future', 'feeling grateful', 'positively spirited', 
        'renewed faith', 'hopeful environment', 'free-spirited', 'beaming with joy', 
        'good progress', 'embracing hope', 'positive drive', 'joyful anticipation', 
        'enthusiastically engaged', 'feeling supported', 'feeling hopeful about recovery', 
        'feeling at ease', 'hopeful journey ahead', 'progressing with optimism', 'fueled by hope', 
        'joy-filled atmosphere', 'inspiring recovery', 'renewed outlook', 'feeling grounded', 
        'positive perspective', 'feeling enlightened', 'hopeful determination', 
        'eager for progress', 'encouraged attitude', 'feeling restored', 'optimism building', 
        'positive action', 'recharged', 'elevated', 'hopeful beginning', 'clear perspective',   'improving mood', 'decreased stress', 'reduced anxiety', 
        'enhanced emotional well-being', 'calming effect', 'relieved tension', 
        'increased motivation', 'confidence boost', 'feeling reassured', 
        'increased positivity', 'uplifted spirit', 'hopeful outlook', 
        'better coping', 'improved mental state', 'emotional comfort', 
        'optimistic outlook', 'increased energy', 'emotional stability', 
        'emotional relief', 'heightened sense of control', 'feeling refreshed', 
        'improved self-esteem', 'strengthened resilience', 'better mood regulation', 
        'sense of accomplishment', 'increased self-confidence', 'mental clarity', 
        'feeling more balanced', 'reduced emotional reactivity', 'positive mindset', 
        'restored optimism', 'improved focus', 'feeling grounded', 
        'enhanced relaxation', 'heightened sense of calm', 'greater self-awareness', 
        'feeling centered', 'more emotionally resilient', 'peace of mind', 
        'improved emotional regulation', 'greater emotional insight', 
        'feeling at ease', 'renewed sense of hope', 'strengthened emotional health', 
        'increased self-compassion', 'boosted emotional endurance', 
        'greater self-acceptance', 'mental rejuvenation', 'feeling secure', 
        'positive emotional shift', 'improved stress resilience', 'greater emotional strength', 
        'restored sense of well-being', 'improved emotional balance', 'sense of empowerment', 
        'feeling more content', 'increased relaxation', 'feeling lighter', 
        'improved mood stability', 'more emotionally centered', 'reduced emotional strain', 
        'relaxed state of mind', 'enhanced mood regulation', 'improved coping skills', 
        'renewed sense of purpose', 'feeling more present', 'greater emotional awareness', 
        'enhanced personal strength', 'heightened emotional intelligence', 
        'improved social connections', 'feeling more grounded emotionally', 
        'sense of well-being', 'increased gratitude', 'improved emotional fitness', 
        'feeling more open', 'reduced feelings of overwhelm', 'greater emotional clarity', 
        'improved emotional adaptability', 'sense of emotional freedom', 
        'emotional release', 'enhanced emotional expression', 'feeling of fulfillment', 
        'greater emotional flexibility', 'improved coping with challenges', 
        'feeling more connected', 'increased emotional comfort', 'renewed sense of calm', 
        'greater emotional insight', 'improved relationship with emotions', 
        'feeling more emotionally regulated', 'elevated emotional state', 
        'improved emotional expression', 'mental restoration', 'sense of peace', 
        'enhanced mood lift', 'feeling more hopeful', 'feeling validated', 
        'improved self-compassion', 'greater emotional clarity'
    ],
    
    negative: [
        'deteriorating', 'adverse', 'complications', 'failure', 'critical', 
        'decline', 'worsening', 'unstable', 'non-responsive', 'poor prognosis', 
        'serious', 'unfavorable', 'problematic', 'emergency', 'severe',
        'declining', 'uncontrolled', 'alarming', 'high-risk', 'acute', 
        'unmanageable', 'extensive', 'impairment', 'malfunction', 'unresolved',
        'catastrophic', 'life-threatening', 'rapid decline', 'unpredictable', 'significant setback',
        'dismal', 'distressed', 'non-recoverable', 'critical condition', 'high mortality risk',
        'fatal', 'advanced stage', 'worsened condition', 'negative outcome', 'disabling',
        'unsuccessful treatment', 'compromised', 'worsened symptoms', 'extreme pain', 'inoperable',
        'spreading', 'metastasized', 'uncontrolled bleeding', 'unreliable', 'negative progress',
        'dangerous', 'unfit', 'decompensating', 'disorienting', 'progressively worsening',
        'concerning', 'degenerative', 'irreversible', 'palliative', 'severely impaired',
        'chronic', 'recurring', 'untreatable', 'incurable', 'out of control', 'uncooperative',
        'weak', 'fragile', 'dismal prognosis', 'overwhelming', 'poor recovery', 'permanent damage',
        'toxic', 'debilitating', 'negative response', 'unfit for recovery', 'terminal', 'damaged',
        'incapacitated', 'unsalvageable', 'resistant to treatment', 'unstable condition', 'precarious',
        'unsurvivable', 'complicated', 'aggravated', 'non-resolving', 'severe complication', 'serious impairment',
        'inadequate', 'unresponsive', 'increasing risk', 'progressive condition', 'unfit for treatment',
        'severely compromised', 'escalating', 'irreparable', 'negative reaction', 'problematic outcome',
        'unsatisfactory', 'out of hand', 'damaging', 'incurable condition', 'debilitating side effects',
        'risky', 'uncontrolled condition', 'systemic failure', 'threatening', 'unpredictable outcome',
        'escalating complications', 'failing treatment', 'inconsistent response', 'life-limiting',
        'poor response', 'no improvement', 'continuing decline', 'acute distress', 'critical failure',
        'system breakdown', 'irreversible deterioration', 'dangerously high', 'worsening symptoms',
        'slow decline', 'severe deterioration', 'spreading infection', 'increased severity', 'chronic pain',
        'progressive decline', 'hopeless', 'no relief', 'compromised immune system', 'unsteady', 
        'non-recovering', 'severe loss', 'growing concern', 'severe pain', 'major setback', 'collapsed', 
        'increasing damage', 'non-responsive system', 'deteriorating health', 'slow progression', 'failed',
        'unstable recovery', 'critical stage', 'negative developments', 'sustained harm', 'unmet recovery goals',
        'lost function', 'devastating', 'irreversible harm', 'increasing complications', 'negative side effects',
        'failure to improve', 'no improvement seen', 'unresolved issues', 'unsuccessful recovery', 'unfit for surgery',
        'seriously ill', 'disabling condition', 'worsened prognosis', 'unmanageable symptoms', 'high morbidity', 
        'declining health', 'severe loss of function', 'progressive pain', 'decreased mobility', 'progressive failure',
        'loss of stability', 'excessive symptoms', 'failing organs', 'substantial damage', 'compromised function',
        'major complications', 'untreatable condition', 'terminal prognosis', 'pervasive', 'limited recovery',
        'difficult to treat', 'profound impairment', 'declining performance', 'failing intervention', 
        'threatening symptoms', 'sustained degradation', 'increasing risk of complications', 'unhealed wound', 
        'massive complications', 'disastrous', 'fatal condition', 'worsened condition after treatment', 'deep pain',
        'complete breakdown', 'toxic reaction', 'progressive weakness', 'unmanageable pain', 'deadly', 'destructive',
        'non-repairable', 'debilitated', 'failed healing', 'uncontrollable', 'increasing inflammation', 'critical event',
        'increasingly severe', 'irreparably damaged', 'worsened infection', 'compromised health status', 
        'rapidly worsening', 'evolving crisis', 'deadly complication', 'disintegrating', 'failure to recover',
        'high morbidity risk', 'unresolvable', 'deteriorating function', 'damaging process', 'unresponsive state',
        'non-recoverable loss', 'decreasing response', 'chronic deterioration', 'discontinuing', 'unsatisfactory prognosis',
        'terminal symptoms', 'complex issue', 'major injury', 'total failure', 'irreversibly harmed', 'prolonged suffering',
        'ongoing damage', 'mortal risk', 'treatment resistance', 'severe adverse effects', 'terminal decline', 
        'nonfunctional', 'catastrophic event', 'collapsed system', 'severe disability', 'unstable prognosis',
        'dissolving', 'seriously compromised', 'morbidity', 'impending failure', 'devastating condition', 
        'negative health outcome', 'unmanageable risk', 'complicated disease', 'escalating problems', 'long-term complications', 
        'unremitting', 'failure of response', 'non-recoverable damage', 'breakdown in health', 'uncontrolled progression',
        'high death risk', 'major health risk', 'irreversible impairment', 'failing function', 'catastrophic failure',
        'depressed function', 'severe symptoms', 'extensive injury', 'grave concern', 'unsalvageable condition',
        'critical condition worsening', 'non-regenerating', 'terminal illness', 'untreatable illness', 
        'major dysfunction', 'palliative care needed', 'incapacitating', 'complete deterioration', 'compounded issues',
        'increasingly critical', 'unrelenting', 'no viable treatment', 'acute crisis', 'unresolved condition', 
        'seriously affected', 'fatal injuries', 'fatal disease', 'severe pathology', 'unrecoverable condition',
        'critical health crisis', 'intractable symptoms', 'unrelenting disease', 'uncontrollable illness', 
        'negative symptom progression', 'severe compromise', 'severe metabolic disorder', 'degenerative disease',
        'treatment-resistant', 'death risk', 'unsalvageable damage', 'advanced impairment', 'unresponsive health status',
        'escalating health risks', 'severe trauma', 'devastating symptoms', 'irreversible health effects', 'untreated',
        'toxic condition', 'non-reparable tissue', 'uncontrolled illness', 'deterioration at an alarming rate', 'terminal stage',
        'chronic condition worsening', 'severe trauma', 'non-responsive symptoms', 'failed intervention', 'disastrous outcome',         'anxious', 'worried', 'stressed', 'fearful', 'uncertain', 
        'discouraged', 'distraught', 'frustrated', 'concerned', 
        'nervous', 'apprehensive', 'disheartened', 'unsettled', 'distressed',
        'angry', 'hopeless', 'disappointed', 'overwhelmed', 'guilty', 
        'helpless', 'uncomfortable', 'irritated', 'restless', 'panicked',
        'fearful of complications', 'disillusioned', 'uneasy', 'insecure', 'troubled', 
        'burdened', 'shocked', 'suffering', 'in pain', 'overcome by fear', 
        'helplessness', 'tense', 'agitated', 'frantic', 'disturbed',
        'apprehensive about treatment', 'deeply concerned', 'confused', 'dismayed', 'regretful',
        'lost', 'isolated', 'vulnerable', 'worried about prognosis', 'sickened', 
        'unwell', 'inadequate', 'empty', 'fear-stricken', 'paranoid', 'shaky', 
        'doubtful', 'hesitant', 'resigned', 'anguished', 'shattered', 
        'defeated', 'withdrawn', 'unhappy', 'tired', 'discomforted', 
        'distracted', 'dissatisfied', 'distressed by the situation', 'scared', 
        'deflated', 'disoriented', 'trapped', 'uncertain of future', 'angry at situation', 
        'in despair', 'unsettled thoughts', 'numb', 'dissatisfied with treatment', 
        'frustrated by limitations', 'discomforted by symptoms', 'fearful of the unknown', 
        'in panic', 'scared of complications', 'mentally exhausted', 'feeling abandoned', 
        'emotionally drained', 'regretful decisions', 'feeling unsupported', 'anxious about outcome', 
        'feeling cursed', 'restless due to pain', 'dreadful', 'haunted by thoughts', 
        'mentally stressed', 'exhausted by fear', 'desperate', 'feeling inferior', 
        'unmotivated', 'discouraged by setbacks', 'overwhelmed by stress', 'depressed', 
        'uneasy about diagnosis', 'resentful', 'increasingly frustrated', 'pessimistic', 
        'disappointed in progress', 'heartbroken', 'anguished over condition', 'disenchanted', 
        'sorrowful', 'grieving', 'disconnected', 'unfit', 'isolated from others', 
        'alienated', 'feeling betrayed', 'doubtful about care', 'hurt', 'distressed by uncertainty', 
        'paralyzed by fear', 'pessimistic about future', 'burdened with worry', 'overloaded', 
        'dismayed by results', 'unsure of the next steps', 'panicking over symptoms', 'aggravated', 
        'fearful of the future', 'disillusioned with process', 'dejected', 'in pain and frustration', 
        'hopeless about improvement', 'feeling a lack of control', 'discomfort in treatment', 
        'overwhelmed by responsibility', 'exasperated', 'disillusioned by care', 
        'emotional turmoil', 'shocked by diagnosis', 'paralyzed by uncertainty', 'exhausted by fear', 
        'in agony', 'depressed about diagnosis', 'feeling trapped by situation', 'resenting the situation', 
        'afraid of the future', 'grief-stricken', 'fretful', 'on edge', 'under distress', 
        'burdened with emotional weight', 'unrested', 'exhausted from stress', 'discontent', 
        'fearing the worst', 'disheartened by delays', 'resentful about condition', 'dreadful feelings', 
        'feeling overwhelmed by pain', 'mentally defeated', 'nervous breakdown', 'hopeless outlook', 
        'overcome with anxiety', 'mentally fatigued', 'psychologically stressed', 'emotionally unstable', 
        'insecure about health', 'defensive', 'discouraged by setbacks', 'uncomfortable in body', 
        'agitated with symptoms', 'oppressed by illness', 'constantly worried', 'afraid of worsening', 
        'strained', 'nervous about results', 'fearful of worsening health', 'dissatisfied with progress', 
        'experiencing extreme stress', 'at the mercy of fear', 'feeling incapacitated', 'negative outlook', 
        'helpless under circumstances', 'tired of fighting', 'grieved over situation', 'afraid to seek help', 
        'grieving over health', 'dissatisfied with current care', 'paralyzed by doubt', 'constantly worried', 
        'spiritually exhausted', 'burdened with hopelessness', 'nervous about treatments', 
        'irritable with symptoms', 'scared of unknown outcomes', 'unsure of results', 'disheartened by lack of progress', 
        'unable to cope with anxiety', 'unsettled with findings', 'grief over uncertainty', 
        'mentally crushed', 'feeling weak', 'on edge from symptoms', 'nervously awaiting news', 
        'uncertain about improvement', 'feeling helpless in recovery', 'apprehensive about procedure', 
        'fearing the inevitable', 'nervous about complications', 'dreading further symptoms', 'unwilling to accept', 
        'mentally consumed by illness', 'reluctant to proceed', 'feeling abandoned by care team', 
        'fearful of new diagnoses', 'stressed about future health', 'uneasy about prognosis', 'feeling restless in care'
    ],
    
    neutral: [
        'ongoing', 'monitored', 'observed', 'assessed', 'evaluated', 
        'investigated', 'reviewed', 'scheduled', 'under examination', 
        'follow-up', 'considered', 'awaiting', 'under observation', 'consulted',
        'diagnosed', 'examined', 'documented', 'studied', 'checked', 
        'planned', 'recommended', 'referenced', 'followed up', 'proposed',
        'observed', 'tracked', 'reported', 'measured', 'updated', 
        'noted', 'confirmed', 'recorded', 'discussed', 'planned for',
        'assisted', 'interviewed', 'analyzed', 'collected', 'confirmed diagnosis',
        'monitored condition', 'scheduled appointment', 'evaluated risks', 'referred',
        'further investigation', 'considering', 'processed', 'verified', 'pending',
        'pending results', 'received', 're-examined', 'ordered', 'provided',
        'diagnostic testing', 'evaluated response', 'checked for', 'pending results',
        'prescribed', 'evaluated history', 'notified', 'reviewing data', 'awaiting response',
        'under treatment', 'to be examined', 'waiting', 'scheduled tests', 'reviewing history',
        'under care', 'received treatment', 'in progress', 'evaluating symptoms', 'assessing treatment',
        'to be monitored', 'waiting for results', 'assisting', 'to be referred', 'evaluating progress',
        'noticing', 'given advice', 'consultation scheduled', 'taking notes', 'analyzing symptoms',
        'advised', 'referred for', 'submitted', 'recording', 'doing tests', 'consulting',
        'being treated', 'looking into', 'continued monitoring', 'rechecked', 'planned care',
        'undergoing tests', 'preliminary results', 'plan of care', 'to be confirmed', 'scheduled follow-up',
        'initiating treatment', 'started medication', 'recording data', 'reexamined', 'in evaluation',
        'reviewing plan', 'further studies', 'patients condition', 'checked history', 'screened',
        'response observed', 'treatment adjustment', 'plan discussed', 'scheduled procedures', 
        'making adjustments', 'therapy initiation', 'care plan', 'medical investigation', 'scheduled procedures',
        'referrals made', 'assessed health', 'considering therapy', 'taking action', 'ongoing assessment', 
        'progress review', 'monitoring progress', 'performing tests', 'observing trends', 'care plan reviewed',
        'discussions held', 'examined response', 'considered options', 'data gathered', 'reviewed results',
        'measuring progress', 'checked vital signs', 'interim assessment', 'tracked changes', 'measuring effectiveness',
        'notifying team', 'evaluating situation', 'doing follow-up', 'expected results', 'waiting for update',
        'attention required', 'testing results', 'final evaluation', 'care under review', 'further action considered',
        'undergoing follow-up', 'investigating further', 'testing pending', 'ongoing care', 'further monitoring',
        'data collection', 'possible outcome', 'tracking progress', 'examine results', 'checking feedback',
        'detailed evaluation', 'received feedback', 'tests completed', 'consultation completed', 'medication review',
        'patient status', 'to be analyzed', 'monitoring trends', 'care pathway', 'noted response', 'prescribed medication',
        'care under review', 'treatment plan', 'clinical assessment', 'care process', 're-examining',
        'health check', 'checking progress', 'confirmed observations', 'care coordination', 'analyzing reports',
        'treatment response', 'completed tests', 'follow-up completed', 'observing response', 'examining options',
        'under clinical review', 'tracking symptoms', 'treatment evaluation', 'assessing results', 'waiting response',
        'review plan', 'completing tests', 'diagnosis confirmed', 'response monitored', 'testing underway',
        'expected progress', 'medication adjustment', 'preliminary diagnosis', 'reviewed treatment', 'condition monitored',
        'new medication', 'looking for patterns', 'examining symptoms', 'tests initiated', 'team review',
        'review progress', 'procedure planned', 'care provided', 'waiting on test', 'final diagnosis',
        'care recommended', 'review diagnosis', 'routine care', 'current treatment', 'diagnostic review',
        'results pending', 'diagnosis revisited', 'ongoing evaluation', 'clinical pathway', 'undergoing observation',
        'patient reviewed', 'checking patient status', 'review progress', 'results in progress', 'current health',
        'treatment being managed', 'routine assessment', 'undergoing investigation', 'screening process',
        'final testing', 'treatment response', 'observational care', 'medication review completed', 'checking status',
        'treatment plan reviewed', 'routine follow-up', 'care under observation', 'investigation in progress', 
        'evaluating data', 'ongoing review', 'monitoring care', 'treatment responses', 'tracking data', 
        'routine check', 'patient examination', 'assessment underway', 'clinical testing', 'analyzing care',
        'testing process', 'monitoring symptoms', 'patient in review', 'observed health trends', 'consultation in progress',
        'reviewing patient', 'investigating case', 'diagnostic assessment', 'tracking diagnosis', 'treatment prescribed',
        'investigation status', 'status under monitoring', 'scheduled observation', 'condition under review',
        'under consideration', 'health report', 'reviewing history', 'under health check', 'medical review', 
        'medication under review', 'care routine', 'progress report', 'reviewing results', 'ongoing investigation', 
        'patient in progress', 'pending action', 'medical checks', 'tracking condition', 'treatment status', 
        'review of options', 'checked case', 'ongoing treatment', 'considering next steps', 'under care management',
        'scheduled diagnosis', 'under investigation'
    ],
    
    cautionary: [
        'warning', 'alert', 'precautionary', 'concern', 'notable', 
        'critical condition', 'risk', 'monitor closely', 'doubtful', 
        'high-risk', 'pending evaluation', 'urgent attention', 'watchful',
        'suspected', 'uncertain', 'potential', 'pending results', 
        'caution', 'alerted', 'evaluating', 'concerned', 'unsettled', 
        'sensitive', 'critical', 'at risk', 'to be careful', 'imminent danger',
        'alarm', 'hazard', 'to be observed', 'unsure', 'preliminary risk',
        'condition under investigation', 'possible complication', 'potential concern', 'warning signs',
        'urgency', 'close observation', 'increased risk', 'delayed response', 'possible deterioration',
        'unpredictable', 'monitored carefully', 'medical alert', 'extra caution', 'to be cautious', 
        'watch for', 'immediate concern', 'serious consideration', 'probable risk', 'examine carefully',
        'suspect complications', 'monitoring needed', 'critical alert', 'under watch', 'treatment under review',
        'risk of progression', 'proceed with caution', 'pending outcome', 'increased surveillance', 
        'take precautions', 'possible emergency', 'deterioration likely', 'imminent risk', 'subject to further review',
        'under scrutiny', 'to be monitored', 'careful observation required', 'monitor status', 'follow closely',
        'expected complications', 'susceptible', 'considerable concern', 'unfavorable trend', 'patient instability',
        'investigating closely', 'need for surveillance', 'dangerous condition', 'outcome uncertain', 'immediate action',
        'to be reconsidered', 'alertness required', 'sensitive to changes', 'possible relapse', 'adverse signs',
        'considerable risk', 'high alert', 'monitor for deterioration', 'precarious situation', 'insecure state',
        'at significant risk', 'possible reversal', 'concern over progression', 'testing necessary', 'risk assessment ongoing',
        'unstable', 'unsteady', 'pending action', 'potential complications', 'checking for decline', 'observing outcome',
        'vigilance advised', 'prolonged risk', 'critical threshold', 'likely complications', 'need for caution',
        'under evaluation', 'patient stability questionable', 'outcome pending', 'watchful waiting', 'danger of worsening',
        'at risk for', 'further assessment required', 'outlook uncertain', 'immediate review', 'suspected deterioration',
        'preliminary finding', 'caution advised', 'reviewed for', 'impaired function', 'responding poorly', 
        'critical review', 'examine with caution', 'high concern', 'to be checked frequently', 'pending further tests',
        'serious warning', 'delayed intervention', 'possible setbacks', 'critical case', 'emergency caution', 'doubtful prognosis',
        'evaluating changes', 'observe carefully', 'continue observation', 'under careful monitoring', 'reaction uncertain',
        'clinical concern', 'likely progression', 'under consideration for', 'heightened risk', 'observing condition closely',
        'examination in progress', 'tests needed', 'no clear response', 'expected decline', 'possible delay in treatment',
        'ongoing risk', 'close monitoring required', 'uncertain response', 'potential reaction', 'not yet stabilized',
        'risk for complications', 'to be confirmed', 'further monitoring', 'serious concern', 'investigation pending',
        'future risk', 'to be reviewed', 'not yet resolved', 'watch closely', 'increased care needed', 'urgent care advised',
        'close attention required', 'risk of escalation', 'heightened awareness', 'testing to determine', 're-evaluating condition',
        'at risk of failure', 'clinical review needed', 'concern over progression', 'still in question', 'to be ruled out',
        'extreme caution', 'pending decision', 'condition not stable', 'prolonged concern', 'treatment under consideration',
        'warning signs noted', 'urgent review', 'urgent care needed', 'deteriorating risk', 'critical status',
        'at high likelihood of', 'possible side effects', 'imminent concern', 'be mindful of', 'cautionary step',
        'not ruled out', 'special caution needed', 'risk of harm', 'reaction to treatment unclear', 'unexpected decline',
        'likely complication', 'continuous monitoring required', 'failure expected', 'close follow-up', 'immediate response needed',
        'requires evaluation', 'increasing concern', 'needs reassessment', 'possible worsening', 'at risk for complications',
        're-evaluate next steps', 'monitor progression', 'critical watch', 'condition worsening', 'increased vigilance',
        'monitoring advised', 'need for further checks', 'close examination', 'further action pending', 'review expected',
        'serious condition suspected', 'decision pending', 'under critical care', 'patients response uncertain', 
        'concern raised', 'concern over future treatment', 'heightened awareness needed', 'requires constant attention', 
        'looking for changes', 'complications suspected', 'special monitoring required', 'under critical review', 
        'approaching risk', 'urgent situation', 'needs immediate evaluation', 'critical treatment required', 'precautionary approach',
        'increased frequency of checks', 'warning symptoms', 'decision pending review', 'unresolved concern', 'at significant risk'
    ]
    


    
  };
  