export const cmeCourses = [
    {
      id: 1,
      title: 'Malaria Management Updates 2024',
      category: 'Infectious Disease',
      credits: 2,
      duration: '2 hours',
      lastUpdated: '2024-03-15',
      difficulty: 'Intermediate',
      component: 'Malaria',
      highlights: [
        'Latest WHO guidelines',
        'Drug resistance patterns',
        'Case studies',
      ],
    },
    {
      id: 2,
      title: 'Modern TB Treatment Protocols',
      category: 'Pulmonology',
      credits: 3,
      duration: '3 hours',
      lastUpdated: '2024-02-20',
      difficulty: 'Advanced',
      component: 'TB',
      highlights: [
        'MDR-TB management',
        'Pediatric cases',
        'Prevention strategies',
      ],
    },
    {
      id: 3,
      title: 'Postpartum Hemorrhage CME',
      category: 'Obstetrics',
      credits: 1,
      duration: '1 hour',
      lastUpdated: '2024-01-10',
      difficulty: 'Basic',
      component: 'Postpartum Hemorrhage',
      highlights: ['Management techniques', 'Case studies'],
    },
    {
      id: 4,
      title: 'Heart Failure: From Diagnosis to Treatment',
      category: 'Cardiology',
      credits: 3,
      duration: '2.5 hours',
      lastUpdated: '2024-03-10',
      difficulty: 'Advanced',
      component: 'Heart Failure',
      highlights: [
        'Early detection of heart failure',
        'Modern treatment protocols',
        'Advanced therapies and devices',
      ],
    },
    {
      id: 5,
      title: 'Managing Chronic Pain: Best Practices for Doctors',
      category: 'Pain Management',
      credits: 2,
      duration: '2 hours',
      lastUpdated: '2024-03-05',
      difficulty: 'Intermediate',
      component: 'Chronic Pain',
      highlights: [
        'Comprehensive pain management strategies',
        'Opioid alternatives and their effectiveness',
        'Understanding the biopsychosocial model of pain',
      ],
    },
    {
      id: 6,
      title: 'Pediatric Emergencies: Recognizing Critical Symptoms Early',
      category: 'Pediatrics',
      credits: 3,
      duration: '3 hours',
      lastUpdated: '2024-02-22',
      difficulty: 'Intermediate',
      component: 'Pediatrics Emergencies',
      highlights: [
        'Early signs of critical pediatric emergencies',
        'Rapid intervention techniques',
        'Pediatric trauma care updates',
      ],
    },
    {
      id: 7,
      title: 'Practical Dermatology: From Acne to Skin Cancer',
      category: 'Dermatology',
      credits: 2,
      duration: '2 hours',
      lastUpdated: '2024-01-30',
      difficulty: 'Basic',
      component: 'Dermatology',
      highlights: [
        'Latest in acne treatments',
        'Spotting and diagnosing skin cancer early',
        'Advances in dermatological treatments and procedures',
      ],
    },
    {
      id: 8,
      title: 'Emergency Care for Stroke: Acting Fast Saves Lives',
      category: 'Neurology',
      credits: 3,
      duration: '2.5 hours',
      lastUpdated: '2024-02-18',
      difficulty: 'Advanced',
      component: 'Stroke Care',
      highlights: [
        'Recognizing stroke symptoms quickly',
        'Latest thrombolytic therapies',
        'Post-stroke rehabilitation strategies',
      ],
    },
    {
      id: 9,
      title: 'Geriatric Care: Managing the Aging Population with Compassion',
      category: 'Geriatrics',
      credits: 2,
      duration: '2 hours',
      lastUpdated: '2024-03-12',
      difficulty: 'Intermediate',
      component: 'Geriatrics Care',
      highlights: [
        'Caring for elderly patients with dementia and other cognitive disorders',
        'Preventing falls and fractures in older adults',
        'Polypharmacy risks and best practices for medication management',
      ],
    },
    {
      id: 10,
      title: 'Cancer Screening and Early Detection: The Key to Saving Lives',
      category: 'Oncology',
      credits: 3,
      duration: '3 hours',
      lastUpdated: '2024-03-01',
      difficulty: 'Advanced',
      component: 'Cancer Screening',
      highlights: [
        'Updated guidelines for breast and colon cancer screening',
        'Early detection technologies in oncology',
        'Genetic testing and its role in prevention',
      ],
    },
    {
      id: 11,
      title: 'Advanced Trauma Life Support (ATLS) Refresher Course',
      category: 'Emergency Medicine',
      credits: 4,
      duration: '4 hours',
      lastUpdated: '2024-02-25',
      difficulty: 'Advanced',
      component: 'ATLS',
      highlights: [
        'Essential trauma care principles for healthcare professionals',
        'Management of trauma patients in the first hour (Golden Hour)',
        'Advanced airway and fluid resuscitation techniques',
      ],
    },
    {
      id: 12,
      title: 'Innovations in Neurosurgery: From Robotics to Regenerative Medicine',
      category: 'Neurosurgery',
      credits: 3,
      duration: '3.5 hours',
      lastUpdated: '2024-03-08',
      difficulty: 'Advanced',
      component: 'Neurosurgery',
      highlights: [
        'Advancements in minimally invasive neurosurgery techniques',
        'Robotic surgery in neurosurgical procedures',
        'The role of stem cells and regenerative medicine in neurological conditions',
      ],
    },
    {
      id: 13,
      title: 'Infectious Disease Management: Navigating the Global Threats',
      category: 'Infectious Disease',
      credits: 2,
      duration: '2 hours',
      lastUpdated: '2024-01-20',
      difficulty: 'Intermediate',
      component: 'Infectious Diseases',
      highlights: [
        'Emerging infectious diseases and their global impact',
        'Antimicrobial resistance: Strategies for combating the crisis',
        'Practical infection control measures in clinical settings',
      ],
    },
    {
      id: 14,
      title: 'Optimizing Mental Health Care in Primary Care Settings',
      category: 'Psychiatry',
      credits: 2,
      duration: '1.5 hours',
      lastUpdated: '2024-03-05',
      difficulty: 'Intermediate',
      component: 'Mental Health Care',
      highlights: [
        'Recognizing mental health conditions in primary care patients',
        'Effective communication and referrals to specialists',
        'Mental health care during crises and emergencies',
      ],
    },
    {
      id: 15,
      title: 'Reproductive Health: Comprehensive Care from Adolescence to Menopause',
      category: 'Obstetrics and Gynecology',
      credits: 3,
      duration: '3 hours',
      lastUpdated: '2024-02-12',
      difficulty: 'Intermediate',
      component: 'Reproductive Health',
      highlights: [
        'Contraception options and counseling',
        'Managing perimenopause and menopause symptoms',
        'Reproductive health education and preventive care',
      ],
    },
    {
      id: 16,
      title: 'The Opioid Crisis: Prevention, Treatment, and Recovery',
      category: 'Addiction Medicine',
      credits: 3,
      duration: '3 hours',
      lastUpdated: '2024-02-28',
      difficulty: 'Intermediate',
      component: 'Opioid Crisis',
      highlights: [
        'Understanding the opioid epidemic and its impact on public health',
        'Evidence-based treatment strategies for opioid use disorder',
        'Prevention and harm reduction strategies',
      ],
    },
    {
      id: 17,
      title: 'Vaccines and Immunization: Updates and New Guidelines',
      category: 'Infectious Disease',
      credits: 2,
      duration: '1.5 hours',
      lastUpdated: '2024-03-01',
      difficulty: 'Basic',
      component: 'Vaccines',
      highlights: [
        'New vaccine recommendations and protocols',
        'Addressing vaccine hesitancy in patients',
        'Updates on COVID-19 and other emerging vaccines',
      ],
    },
    {
      id: 18,
      title: 'Artificial Intelligence in Medicine: Revolutionizing Diagnostics',
      category: 'Technology in Healthcare',
      credits: 3,
      duration: '3 hours',
      lastUpdated: '2024-01-15',
      difficulty: 'Advanced',
      component: 'AI in Medicine',
      highlights: [
        'Introduction to AI and machine learning in healthcare',
        'How AI is transforming diagnostics and treatment plans',
        'Ethical implications and challenges of AI in medicine',
      ],
    },
    {
      id: 19,
      title: 'Managing Hypertension: Best Practices and New Guidelines',
      category: 'Cardiology',
      credits: 2,
      duration: '2 hours',
      lastUpdated: '2024-02-10',
      difficulty: 'Intermediate',
      component: 'Hypertension Management',
      highlights: [
        'Recent guidelines and recommendations for hypertension management',
        'Pharmacological vs non-pharmacological treatments',
        'Dealing with resistant hypertension',
      ],
    },
    {
      id: 20,
      title: 'Improving Patient Outcomes in Diabetes Management',
      category: 'Endocrinology',
      credits: 3,
      duration: '2.5 hours',
      lastUpdated: '2024-03-03',
      difficulty: 'Advanced',
      component: 'Diabetes Care',
      highlights: [
        'New insulin and medication options',
        'Continuous glucose monitoring systems',
        'Best practices for managing diabetic complications',
      ],
    }
  ];
  