export const EMOTION_COMBINATIONS = {
    DISTRESS: {
      emotions: ['anxiety', 'fear', 'pain'],
      summary: "The patient shows significant distress, with anxiety and fear likely triggered by physical discomfort or pain. This may indicate a heightened vulnerability to symptoms and a potential barrier to treatment adherence.",
      traits: "Heightened sensitivity to discomfort, difficulty managing stress, possible avoidance behaviors, and reluctance to engage in care due to fear.",
      emotional_state: "The patient is overwhelmed, potentially in a state of panic, and may experience exacerbated symptoms when faced with treatment-related anxiety.",
      treatment_attitude: "Patient may be hesitant or reluctant to seek treatment due to fear of pain, discomfort, or anticipated treatment experiences.",
      coping_mechanisms: "Common coping strategies include avoidance, withdrawal, or numbing behaviors. They may struggle to initiate or continue treatment without reassurance.",
      social_support: "This patient will likely need strong emotional support, reassurance, and involvement from family or close contacts to overcome distress.",
      health_beliefs: "They may have negative health beliefs or a lack of confidence in the effectiveness of treatment, perceiving their condition as beyond help.",
      motivation: "The primary motivation is a high desire for relief, with an emphasis on escaping discomfort.",
      perceived_barriers: "Fear of pain, treatment-related anxiety, or a lack of clarity about treatment outcomes may prevent them from fully engaging in their care.",
      general_wellbeing: "Significant emotional and physical strain, with compromised wellbeing. This requires a compassionate, patient-centered approach to care.",
      cultural_soc_econ_influences: "Cultural or socioeconomic factors could influence their willingness to seek care, impacting how they respond to healthcare professionals and treatment options."
    },
    SADNESS_COMPLEX: {
      emotions: ['sadness', 'loneliness', 'guilt'],
      summary: "The patient demonstrates a complex emotional state centered around sadness, with feelings of isolation, guilt, and shame that may impact their engagement with care.",
      traits: "Tendency to withdraw, self-blame, and difficulty reaching out for help due to feelings of shame and guilt.",
      emotional_state: "Deep sadness complicated by feelings of isolation and self-reproach, making it difficult to engage fully in treatment.",
      treatment_attitude: "May be reluctant to seek help due to shame or feelings of unworthiness, requiring gentle encouragement and validation.",
      coping_mechanisms: "May engage in self-isolation and have difficulty sharing concerns or seeking support when needed.",
      social_support: "Requires consistent, non-judgmental support while respecting their need for space and dignity.",
      health_beliefs: "May view their condition through a lens of personal fault or failure, complicating their approach to treatment.",
      motivation: "Motivation may be undermined by feelings of hopelessness and self-doubt.",
      perceived_barriers: "Shame and guilt may create significant barriers to seeking and maintaining care.",
      general_wellbeing: "Emotional state may significantly impact overall wellbeing and ability to engage in self-care.",
      cultural_soc_econ_influences: "Cultural attitudes toward mental health and personal responsibility may influence their experience of shame and guilt."
    },
    FRUSTRATION_ANGER: {
      emotions: ['frustration', 'anger', 'disappointment'],
      summary: "The patient exhibits strong feelings of frustration and anger, potentially complicated by disappointment in their health journey.",
      traits: "May show irritability, impatience with treatment progress, and difficulty managing emotional responses to setbacks.",
      emotional_state: "Heightened emotional reactivity with underlying disappointment about their health situation.",
      treatment_attitude: "May express skepticism or resistance due to past disappointments or perceived lack of progress.",
      coping_mechanisms: "Might struggle with emotional regulation and maintaining consistent engagement with treatment plans.",
      social_support: "Will benefit from patient, understanding support that acknowledges their frustrations while encouraging constructive engagement.",
      health_beliefs: "May have developed skepticism about treatment efficacy due to past disappointments.",
      motivation: "Motivation might fluctuate based on perceived progress and setbacks.",
      perceived_barriers: "Frustration with the pace or effectiveness of treatment may create barriers to consistent engagement.",
      general_wellbeing: "Emotional strain may impact overall wellbeing and treatment adherence.",
      cultural_soc_econ_influences: "Cultural expectations and previous healthcare experiences may influence expressions of frustration and anger."
    },
    POSITIVE_ENGAGEMENT: {
      emotions: ['hope', 'joy', 'gratitude'],
      summary: "The patient maintains a positive outlook characterized by hope, joy, and gratitude, with healthy curiosity about their care and pride in their progress.",
      traits: "Demonstrates engagement, optimism, and active interest in understanding and participating in their care.",
      emotional_state: "Emotionally resilient with a balanced, positive approach to health challenges.",
      treatment_attitude: "Shows genuine interest and engagement in treatment, with gratitude for care and pride in progress.",
      coping_mechanisms: "Utilizes positive emotional resources and maintains active engagement in their health journey.",
      social_support: "Effectively engages with support systems while maintaining a sense of personal agency.",
      health_beliefs: "Maintains hopeful but realistic expectations about health outcomes.",
      motivation: "Demonstrates intrinsic motivation fueled by curiosity and positive engagement.",
      perceived_barriers: "Views challenges as opportunities for growth and learning.",
      general_wellbeing: "Positive emotional state contributes to overall wellbeing and treatment engagement.",
      cultural_soc_econ_influences: "Cultural values may support and reinforce positive engagement with healthcare."
    },
    UNCERTAINTY_CONCERN: {
      emotions: ['confusion', 'concern', 'anxiety'],
      summary: "The patient expresses uncertainty about their condition or treatment, accompanied by concern and anxiety about health outcomes.",
      traits: "Shows hesitancy in decision-making and may seek frequent reassurance about treatment choices.",
      emotional_state: "Experiences ongoing uncertainty that may manifest as anxiety and general concern about health.",
      treatment_attitude: "May be cautious about treatment decisions, requiring clear information and support.",
      coping_mechanisms: "Tends to seek information and reassurance to manage uncertainty.",
      social_support: "Benefits from clear communication and consistent support in decision-making.",
      health_beliefs: "May struggle with confidence in treatment decisions due to underlying uncertainty.",
      motivation: "Motivation may be impacted by difficulty making decisions under uncertainty.",
      perceived_barriers: "Uncertainty and concern may delay treatment decisions or engagement.",
      general_wellbeing: "Anxiety about uncertainty may impact overall wellbeing and confidence.",
      cultural_soc_econ_influences: "Cultural approaches to decision-making may influence how uncertainty is experienced and managed."
    },
    EMPOWERED_CURIOUS: {
        emotions: ['empowerment', 'curiosity', 'pride'],
        summary: "The patient exhibits strong self-efficacy and interest in understanding their health condition, coupled with pride in taking an active role in their care.",
        traits: "Shows initiative in learning about their condition, confidence in decision-making, and satisfaction in personal health management.",
        emotional_state: "Engaged and confident, with active interest in understanding and managing their health condition.",
        treatment_attitude: "Proactively engages with treatment options and shows interest in understanding the rationale behind different approaches.",
        coping_mechanisms: "Uses information-seeking and self-advocacy as primary coping strategies, building confidence through knowledge.",
        social_support: "Effectively advocates for needs while maintaining collaborative relationships with healthcare providers.",
        health_beliefs: "Views health as something that can be actively managed and improved through personal effort and understanding.",
        motivation: "Driven by desire to understand and master health management strategies.",
        perceived_barriers: "Sees challenges as opportunities for learning and growth.",
        general_wellbeing: "Maintains positive wellbeing through active engagement and sense of control.",
        cultural_soc_econ_influences: "Educational background and access to resources may influence level of engagement and empowerment."
      },
      
      ANXIETY_DISAPPOINTMENT: {
        emotions: ['anxiety', 'disappointment', 'concern'],
        summary: "The patient shows significant anxiety about their health status, complicated by disappointment with treatment progress or outcomes.",
        traits: "Tendency to anticipate negative outcomes while struggling with setbacks in treatment progress.",
        emotional_state: "Anxious and discouraged, with ongoing concern about health trajectory.",
        treatment_attitude: "May be hesitant about new treatments due to past disappointments while maintaining underlying worry.",
        coping_mechanisms: "May alternate between over-vigilance and withdrawal when facing setbacks.",
        social_support: "Needs reassurance and encouragement, particularly after experiencing setbacks.",
        health_beliefs: "May struggle with maintaining optimism while managing anxiety about outcomes.",
        motivation: "Motivation fluctuates with anxiety levels and experiences of disappointment.",
        perceived_barriers: "Past disappointments may compound anxiety about treatment success.",
        general_wellbeing: "Emotional state may impact overall wellbeing and treatment engagement.",
        cultural_soc_econ_influences: "Previous healthcare experiences may influence expectations and anxiety levels."
      },
      
      RELIEF_GRATITUDE: {
        emotions: ['relief', 'gratitude', 'hope'],
        summary: "The patient experiences significant relief from symptoms or concerns, leading to feelings of gratitude and renewed hope.",
        traits: "Appreciative of improvements, optimistic about continued progress, and positive in healthcare interactions.",
        emotional_state: "Emotionally uplifted by experienced relief, with strong positive feelings toward care providers.",
        treatment_attitude: "Highly receptive to treatment recommendations, motivated by experienced improvements.",
        coping_mechanisms: "Builds on positive experiences to maintain optimism and treatment engagement.",
        social_support: "Actively appreciates and engages with support systems, strengthening therapeutic relationships.",
        health_beliefs: "Strengthened belief in treatment efficacy based on experienced relief.",
        motivation: "Motivated by positive outcomes and desire to maintain improvements.",
        perceived_barriers: "Reduced perception of barriers due to positive experiences.",
        general_wellbeing: "Improved emotional and physical wellbeing reinforcing positive outlook.",
        cultural_soc_econ_influences: "Cultural expressions of gratitude may influence therapeutic relationships."
      },
      
      FEAR_CONFUSION: {
        emotions: ['fear', 'confusion', 'anxiety'],
        summary: "The patient experiences significant fear about their condition, compounded by confusion about treatment options or health status.",
        traits: "Shows hesitancy in decision-making, seeks frequent clarification, and may experience decision paralysis.",
        emotional_state: "Anxious and uncertain, with fear potentially overwhelming ability to process information.",
        treatment_attitude: "May struggle with treatment decisions due to fear of making wrong choices.",
        coping_mechanisms: "May seek excessive reassurance or avoid making decisions altogether.",
        social_support: "Needs clear, patient explanation and emotional support in decision-making.",
        health_beliefs: "Uncertainty about condition may increase fear and anxiety about outcomes.",
        motivation: "Fear may either paralyze or motivate, depending on support and understanding.",
        perceived_barriers: "Confusion about options may amplify fears about treatment.",
        general_wellbeing: "Emotional stress may impact ability to engage effectively with care.",
        cultural_soc_econ_influences: "Language barriers or health literacy may contribute to confusion and fear."
      },
      
      LOVE_HOPE: {
        emotions: ['love', 'hope', 'gratitude'],
        summary: "The patient demonstrates strong positive emotions centered around supportive relationships and optimism for the future.",
        traits: "Shows strong connection to support system, maintains positive outlook, and appreciates care received.",
        emotional_state: "Emotionally secure with strong positive attachments supporting recovery.",
        treatment_attitude: "Approaches treatment with optimism, supported by strong relationships.",
        coping_mechanisms: "Utilizes positive relationships and emotional connections as primary coping strategies.",
        social_support: "Strong family/social connections provide emotional foundation for treatment.",
        health_beliefs: "Views health journey through lens of hope and positive relationships.",
        motivation: "Motivated by connection to loved ones and positive future outlook.",
        perceived_barriers: "Strong support system helps overcome treatment challenges.",
        general_wellbeing: "Positive emotional state contributes to overall wellbeing.",
        cultural_soc_econ_influences: "Family and cultural values may strengthen positive emotional state."
      },
      
      SADNESS_ANGER: {
        emotions: ['sadness', 'anger', 'frustration'],
        summary: "The patient experiences complex emotional state combining grief or sadness with anger about their health situation.",
        traits: "May alternate between withdrawal and emotional outbursts, struggling with acceptance.",
        emotional_state: "Fluctuates between sadness and anger, with underlying frustration about circumstances.",
        treatment_attitude: "May resist treatment due to anger while feeling sad about health changes.",
        coping_mechanisms: "May struggle with consistent coping strategies due to emotional fluctuations.",
        social_support: "Needs patient, understanding support that can handle emotional variations.",
        health_beliefs: "May view health situation through lens of loss and injustice.",
        motivation: "Motivation may be impacted by emotional struggles.",
        perceived_barriers: "Emotional state may create barriers to consistent engagement.",
        general_wellbeing: "Complex emotional state impacts overall wellbeing and coping.",
        cultural_soc_econ_influences: "Cultural expressions of grief and anger may influence coping."
      },
      
      CURIOSITY_CONCERN: {
        emotions: ['curiosity', 'concern', 'anxiety'],
        summary: "The patient shows active interest in understanding their condition while maintaining underlying concerns.",
        traits: "Balances information-seeking with worry about implications of knowledge gained.",
        emotional_state: "Engaged but cautious, with anxiety potentially affecting information processing.",
        treatment_attitude: "Actively seeks to understand treatment while managing concerns about outcomes.",
        coping_mechanisms: "Uses information-gathering as coping strategy while managing anxiety.",
        social_support: "Benefits from supportive education that addresses underlying concerns.",
        health_beliefs: "Values understanding while managing worry about health implications.",
        motivation: "Motivated by desire to understand but may be limited by anxiety.",
        perceived_barriers: "Concern may create barriers to fully utilizing information gained.",
        general_wellbeing: "Balance between engagement and anxiety affects overall wellbeing.",
        cultural_soc_econ_influences: "Educational background and health literacy influence engagement."
      },
      
      SHAME_ANXIETY: {
        emotions: ['shame', 'anxiety', 'fear'],
        summary: "The patient experiences significant shame about their condition combined with anxiety about treatment and outcomes.",
        traits: "May avoid care due to shame while experiencing high anxiety about health status.",
        emotional_state: "Emotionally vulnerable with strong self-consciousness affecting care engagement.",
        treatment_attitude: "May delay or avoid treatment due to shame despite anxiety about health.",
        coping_mechanisms: "May use avoidance as primary coping strategy despite increasing anxiety.",
        social_support: "Needs non-judgmental support that addresses both shame and anxiety.",
        health_beliefs: "Shame may color health beliefs and increase anxiety about seeking care.",
        motivation: "Motivation complicated by shame despite anxiety about health needs.",
        perceived_barriers: "Shame creates significant barriers to accessing needed care.",
        general_wellbeing: "Emotional distress significantly impacts overall wellbeing.",
        cultural_soc_econ_influences: "Cultural attitudes toward condition may increase shame."
      },
      
      PRIDE_EMPOWERMENT: {
        emotions: ['pride', 'empowerment', 'joy'],
        summary: "The patient demonstrates strong sense of achievement and personal agency in managing their health.",
        traits: "Shows confidence in health management, satisfaction with progress, and positive self-image.",
        emotional_state: "Emotionally strong and confident, with positive outlook on health journey.",
        treatment_attitude: "Actively engaged in treatment with sense of personal accomplishment.",
        coping_mechanisms: "Uses sense of achievement and control as primary coping strategies.",
        social_support: "Maintains positive relationships while demonstrating independence.",
        health_beliefs: "Strong sense of self-efficacy in managing health outcomes.",
        motivation: "Highly motivated by sense of achievement and control.",
        perceived_barriers: "Views challenges as opportunities to demonstrate capability.",
        general_wellbeing: "Positive emotional state enhances overall wellbeing.",
        cultural_soc_econ_influences: "Personal values and achievements influence engagement."
      },
      
      GUILT_LONELINESS: {
        emotions: ['guilt', 'loneliness', 'sadness'],
        summary: "The patient struggles with guilty feelings about their health situation while experiencing isolation.",
        traits: "Tendency to self-blame combined with difficulty reaching out for support.",
        emotional_state: "Emotionally isolated with self-critical thoughts affecting wellbeing.",
        treatment_attitude: "May view treatment through lens of personal failure and isolation.",
        coping_mechanisms: "May struggle with seeking help due to guilt and isolation.",
        social_support: "Needs active outreach while respecting emotional vulnerability.",
        health_beliefs: "May view health challenges as personal failures.",
        motivation: "Motivation impacted by guilt and feelings of isolation.",
        perceived_barriers: "Emotional state creates barriers to seeking support.",
        general_wellbeing: "Emotional isolation significantly impacts overall wellbeing.",
        cultural_soc_econ_influences: "Cultural attitudes toward illness may influence guilt."
      }
};